INSERT OR REPLACE INTO LocalizedText(Language, Tag, Text) VALUES --Policeis
('de_DE', 'LOC_POLICY_PRIMITIVE_COMMUNE_NAME',
'Urkommune|Urkommune|Urkommune|Urkommune|Urkommune'),

('de_DE', 'LOC_POLICY_PRIMITIVE_COMMUNE_DESCRIPTION',
'+1 [ICON_Food] Nahrung in allen Städten.'),

('de_DE', 'LOC_POLICY_LIBERALISM_DESCRIPTION_ZJ',
'+1 [ICON_Food] Nahrung und +1 [ICON_Production] Produktion in allen Städten.'),

('de_DE', 'LOC_POLICY_URBAN_RENEWAL_NAME',
'Stadterneuerung|Stadterneuerung|Stadterneuerung|Stadterneuerung|Stadterneuerung'),

('de_DE', 'LOC_POLICY_URBAN_RENEWAL_DESCRIPTION',
'+50% [ICON_Production] Produktion für Gebäude im Stadtzentrum.'),

('de_DE', 'LOC_POLICY_VETERANCY_DESCRIPTION_ZJ',
'+30% [ICON_Production] Produktion für Flugplatz-Bezirke, Lager-Bezirke und Hafen-Bezirke sowie deren jeweiligen Gebäude.'),

('de_DE', 'LOC_POLICY_INTEGRATED_SPACE_CELL_DESCRIPTION_ZJ',
'+15 % [ICON_Production] Produktion für Weltraumrennen-Projekte, für Städte mit Militärakademie oder Hangar oder Seehafen.'),

('de_DE', 'LOC_POLICY_MILITARY_RESEARCH_EXPANSION1_DESCRIPTION_ZJ',
'Militärakademien, Seehäfen und Renaissance-Mauern bringen +3 [ICON_Science] Wissenschaft.');
