--------------------------------------------------------------------------------------------------------------------------
-- LocalizedText
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Tag, 																		Language,					Text)
VALUES
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------
		("LOC_FEATURE_SUK_GRANDCANYON_NAME",  										"de_DE",
		"Grand Canyon"																),
		("LOC_FEATURE_SUK_GRANDCANYON_DESCRIPTION",  								"de_DE",
		"Unpassierbares Naturwunder über drei Geländefelder. Gewährt +1 [ICON_FOOD] Nahrung, +1 [ICON_CULTURE] Kultur für angrenzende Felder. Nachdem das Industriezeitalter erreicht wurde,  erhalten Städte +4 [ICON_Tourism] Tourismus für jedes Feld des Grand Canyons im Besitz. Bietet Süßwasser."																),
		("LOC_FEATURE_SUK_GRANDCANYON_QUOTE",  										"de_DE",
		"“Mit dem Grand Canyon verfügt Arizona über ein Naturwunder, das in seiner Art auf der ganzen Welt seinesgleichen sucht. Man kann es nicht verbessern. Die Zeitalter haben an ihm gearbeitet, und der Mensch kann ihn nur beschädigen.”[NEWLINE]– Theodore Roosevelt"																),
		("LOC_PEDIA_FEATURES_PAGE_FEATURE_SUK_GRANDCANYON_CHAPTER_HISTORY_PARA_1",  "de_DE",
		"Der Grand Canyon ist eines der größten geologischen Schauspiele der Erde, die es gibt. Seine Weite ist atemberaubend, und die Beweise, die er über die Erdgeschichte liefert, sind von unschätzbarem Wert. Seine geologischen Aufzeichnungen umfassen alle vier Epochen der Entwicklungsgeschichte der Erde, vom Präkambrium bis zum Känozoikum. Die 1,5 km tiefe Schlucht windet sich über 445 km und wurde in 6 Millionen Jahren geologischer Aktivität und Erosion durch den Colorado River geformt. Der Grand Canyon ist weithin bekannt für seine außergewöhnliche natürliche Schönheit und gilt als eine der eindrucksvollsten Landschaften der Welt. Er ist berühmt für seine abgrundtiefe Schlucht, seine tempelartigen Felsen und seine weitläufige, vielfarbige, labyrinthische Topografie. Zu den landschaftlichen Wundern innerhalb der Parkgrenzen gehören Hochebenen, Ebenen, Wüsten, Wälder, Schlackenkegel, Lavaströme, Bäche, Wasserfälle und einer der größten Wildwasserflüsse Amerikas. Der Canyon ist ein außergewöhnliches Beispiel für biologische Umgebungen in unterschiedlichen Höhenlagen, die sich im Laufe des Flusses entwickelt haben und fünf der sieben Lebenszonen Nordamerikas innerhalb der Canyonwände darstellen. Flora und Fauna überschneiden sich in vielen dieser Zonen und sind überall im Canyon zu finden. Seit Tausenden von Jahren ist das Gebiet ununterbrochen von amerikanischen Ureinwohnern bewohnt, die im Canyon und seinen zahlreichen Höhlen Siedlungen bauten. Das Pueblo-Volk betrachtete den Grand Canyon als heilige Stätte und unternahm Pilgerfahrten dorthin. US-Präsident Theodore Roosevelt erklärte das Reservat am 11. Januar 1908 zum US-Nationaldenkmal, und heute ist der Grand-Canyon-Nationalpark eine der wichtigsten Naturattraktionen der Welt, die jährlich etwa fünf Millionen Besucher anlockt.");
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------