
UPDATE LocalizedText
SET Text = "{LOC_PRESERVE_GARDEN_EXCLUSIVE}"||Text
WHERE Tag = "LOC_DISTRICT_PRESERVE_DESCRIPTION";

UPDATE LocalizedText
SET Text = "{LOC_GARDEN_PRESERVE_EXCLUSIVE}"||Text
WHERE Tag = "LOC_DISTRICT_LEU_GARDEN_DESC";