-- 6T_Text_Boosts
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR REPLACE INTO EnglishText
		(Tag,														Text)
VALUES			 ('LOC_BOOST_TRIGGER_6T_CITIZENSHIP',				'Build 2 Theater Square districts.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_CITIZENSHIP',				'Large public gatherings have your urban population debate politics and laws of the city.'),
		('LOC_BOOST_TRIGGER_LONGDESC_CIVIL_ENGINEERING_JNR_6T',		'Higher and faster we build, and these skills shall not be wasted on vanity but achieve convenience for all.'),
				 ('LOC_BOOST_TRIGGER_CONSERVATION_JNR_6T',			'Build 2 Preserve districts.'),
		('LOC_BOOST_TRIGGER_LONGDESC_CONSERVATION_JNR_6T',			'In the face of industrialization it will require a national effort to protect our natural treasures.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_CONSTITUTION',				'Men and women from all walks of life live make our country a bastion of progress. They demand fundamental rights for all to be codified.'),
				 ('LOC_BOOST_TRIGGER_6T_CONSUMERISM',				'Build 2 Seaports.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_CONSUMERISM',				'Goods from all around the world fill your stores. A whole lifestyle can be made out of enjoying them.'),
		('LOC_BOOST_TRIGGER_LONGDESC_ENVIRONMENTALISM_JNR_6T',		'The establishment of a National Park has reminded us of the incredible value that an intact natural environment provides us with.'),
				 ('LOC_BOOST_TRIGGER_6T_ESTATES',					'Build 2 Medieval Walls.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_ESTATES',					'Protecting your possessions is costly. Feudal lords need to organize the economy of their walled holdings more effectively.'),
				 ('LOC_BOOST_TRIGGER_HUMANISM_JNR_UC',				'Earn a Great Writer.'),
		('LOC_BOOST_TRIGGER_LONGDESC_HUMANISM_JNR_UC',				'The inspiration provided by your newly-acquired Great Writer is awakening our people to the power of the individual.'),
				 ('LOC_BOOST_TRIGGER_6T_MERCHANT_LEAGUES',			'Build 2 Commercial Hub districts.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_MERCHANT_LEAGUES',			'Sprawling trade networks have created a wealthy class of merchants. Now they aim to transform these riches into political power.'),
				 ('LOC_BOOST_TRIGGER_6T_MONASTICISM',				'Build a Grove.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_MONASTICISM',				'In a grove surounded by leagues of wilderness, a hermit achieves spiritual enlightenment.'),
		('LOC_BOOST_TRIGGER_LONGDESC_NUCLEAR_PROGRAM_JNR_6T',		'Now that you have secured the critical resources required, your initiative to recruit scientists into a nuclear research program can commence.'),
				 ('LOC_BOOST_TRIGGER_6T_PARLIAMENTARISM',			'Build 3 Amphitheaters.'),
				 ('LOC_BOOST_TRIGGER_6T_PARLIAMENTARISM_JNR_UC',	'Build 2 Assemblies.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_PARLIAMENTARISM',			'Liberal statesmen quote classical writings which say that rule by Many is the correct method through which a country ought to be governed.'),
				 ('LOC_BOOST_TRIGGER_6T_PATRONAGE',					'Build a Medieval era or later wonder.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_PATRONAGE',					'The completion of this grand wonder has noble families competing for your realm''s new glory by commissioning marvellous works on their own.'),
				 ('LOC_BOOST_TRIGGER_6T_POP_CULTURE',				'Build 2 Stadiums.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_POP_CULTURE',				'Mass events in your new stadiums are tranforming the way that culture is experienced and consumed.'),
				 ('LOC_BOOST_TRIGGER_RECORDED_HISTORY_JNR_6T',		'Build 2 Libraries.'),
				 ('LOC_BOOST_TRIGGER_6T_ROMANTICISM',				'Earn a Great Artist.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_ROMANTICISM',				'The blistering pace of modernity sparked nostalgia for a life closer to nature that might or might not have existed once.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_STATE_RELIGION',			'The formation of a religion by your Great Prophet has impressed your leaders. They want to institutionalize it.'),
				 ('LOC_BOOST_TRIGGER_SUFFRAGE_JNR_6T',				'Build 3 Sewers.'),
				 ('LOC_BOOST_TRIGGER_6T_TERRITORY',					'Have 3 Cities.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_TERRITORY',					'As people spread out and settle new regions, you no longer rule over just local community but a realm with vast lands to be marked as yours.'),
				 ('LOC_BOOST_TRIGGER_THEOLOGY_JNR_6T',				'Build 2 Holy Site districts.'),
		('LOC_BOOST_TRIGGER_LONGDESC_THEOLOGY_JNR_6T',				'Debates between the priests of your multiple holy sites are intensifying, demonstrating the need for systematic inquiry.'),
				 ('LOC_BOOST_TRIGGER_6T_TOLERANCE',					'Research the Printing technology.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_TOLERANCE',					'The spread of literature raises awareness of other perspectives, allowing our people to somwhat sanction the acts of pagans and Heathens.'),
		('LOC_BOOST_TRIGGER_LONGDESC_VENTURE_POLITICS_JNR_6T',		'Private-sector partnerships surrounding the development of our drones have led to a new relationship between business and government.'),
				 ('LOC_BOOST_TRIGGER_6T_WARFARE',					'Kill 2 Barbarians.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_WARFARE',					'Gazing upon the corpses the fallen, we realize that there are no true winners in war, only those who remain.'),		
				
				 ('LOC_BOOST_TRIGGER_ADVANCED_BALLISTICS_JNR_6T',	'Own 2 Artillery units.'),
		('LOC_BOOST_TRIGGER_LONGDESC_ADVANCED_BALLISTICS_JNR_6T',	'Our artillery is now powerful enough to strike targets even beyond the horizon. Such firepower will fundamentally change warfare all around.'),
				 ('LOC_BOOST_TRIGGER_6T_ALCHEMY',					'Have the Divine Right civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_ALCHEMY',					'The art of alchemy is bestowed upon us by the Heavens, and it is Heaven''s will that man unlock the secrets of the Earth.'),
				 ('LOC_BOOST_TRIGGER_ASTROLOGY_JNR_6T',				'Build a Monument.'),
		('LOC_BOOST_TRIGGER_LONGDESC_ASTROLOGY_JNR_6T',				'A monument guides our gaze towards the sky and we seek to decipher the higher meaning in the celestial order.'),
		('LOC_BOOST_TRIGGER_LONGDESC_BALLISTICS_JNR_6T',			'Placeholder.'),
		('LOC_BOOST_TRIGGER_LONGDESC_BRONZE_WORKING_JNR_6T',		'Simple metals are seeing widespread use among your people. Maybe they could be combined into a sturdier alloy for tools and weapons.'),
				 ('LOC_BOOST_TRIGGER_6T_BIOLOGY',					'Build 3 Fisheries.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_BIOLOGY',					'Your coastal economy offers many possibilities for scientists to study marine organisms further. Did all life originally come from the ocean?'),
				 ('LOC_BOOST_TRIGGER_6T_CALENDAR',					'Build a Campus district.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_CALENDAR',					'Scholars are starting to gather more frequently around the sites they built to document the passage of seasons.'),
				 ('LOC_BOOST_TRIGGER_6T_CARACOLE',					'Own 2 Pikemen.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_CARACOLE',					'Long pikes make it impossible to charge enemy lines. Our cavalry must learn new tactics to approach them.'),
				 ('LOC_BOOST_TRIGGER_CARTOGRAPHY_JNR_6T',			'Build 3 Harbors.'),
		('LOC_BOOST_TRIGGER_LONGDESC_CASTLES_JNR_6T',				'Our new government’s military advisor suggests noble champions to defend our lands. Perhaps mounting an armored warrior will do the trick?'),
				 ('LOC_BOOST_TRIGGER_CHEMISTRY_JNR_6T',				'Build 2 Chemical Plants.'),
		('LOC_BOOST_TRIGGER_LONGDESC_CHEMISTRY_JNR_6T',				'Being able to produce sulphuric acid industrially has opened up many opportunities to develop your understanding of the elements further.'),
				 ('LOC_BOOST_TRIGGER_6T_COKING',					'Build 3 Lumber Mills.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_COKING',					'An increasing need for charcoal as fuel makes wood rare. Maybe we can enhance rock coal to replace it.'),
		('LOC_BOOST_TRIGGER_LONGDESC_COMBUSTION_JNR_UC',			'Having a source of petrochemicals should lead to many advances. Could they power engines?'),
				 ('LOC_BOOST_TRIGGER_6T_COMPASS',					'Earn a Great Admiral.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_COMPASS',					'With a device showing our bearings precisely even on high seas we would be less dependent on gifted individuals to guide our fleets.'),
		('LOC_BOOST_TRIGGER_LONGDESC_CONSTRUCTION_JNR_UC',			'Completing walls around your city has taught your workers much about construction practices.'),
				 ('LOC_BOOST_TRIGGER_6T_DYNAMITE',					'Have the Civil Engineering civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_DYNAMITE',					'Our engineers desire a more reliable alternative to black powder for blasting rock.'),
				 ('LOC_BOOST_TRIGGER_6T_ECOLOGY',					'Have the Environmentalism civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_ECOLOGY',					'Heightened awareness of the fragility of our environment encourages our scientists to learn more about the complexities of ecosystems.'),
		('LOC_BOOST_TRIGGER_LONGDESC_ELECTRICITY_JNR_UC',			'Your city is now powered. However your scientists are already hard at work on developing ways to transmit power over longer distances.'),
		('LOC_BOOST_TRIGGER_LONGDESC_ENGINEERING_JNR_UC',			'Building a wide variety of mines has demonstrated the principles of engineering needed for Aqueducts and Catapults.'),
				 ('LOC_BOOST_TRIGGER_FLIGHT_JNR_6T',				'Have the Romanticism civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_FLIGHT_JNR_6T',				'Ancient legends of heroes soaring through the air with manmade wings inspire poets and inventors alike.'),
				 ('LOC_BOOST_TRIGGER_6T_GENOMICS',					'Have a level 3 Alliance.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_GENOMICS',					'International cooperation has secured the resources needed to advance the Human Genome Project.'),
		('LOC_BOOST_TRIGGER_LONGDESC_GUNPOWDER_JNR_6T',				'Massive castle walls are nearly impenetrable to even the mightiest engines. Could the fire salts our alchemists speak of break them open?'),
				 ('LOC_BOOST_TRIGGER_6T_HORSE_COLLAR',				'Own 2 Heavy Chariots.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_HORSE_COLLAR',				'Our horses could draw a lot more weight if we distributed it better on their bodies.'),
				 ('LOC_BOOST_TRIGGER_HORSEBACK_RIDING_JNR_6T',		'Build a Horses Pasture.'),
		('LOC_BOOST_TRIGGER_LONGDESC_HORSEBACK_RIDING_JNR_6T',		'Could these tamed creatures carry not just goods but even people?'),
		('LOC_BOOST_TRIGGER_LONGDESC_LASERS_JNR_6T',				'With a dedicated research lab in place, experiments to refine and focus light itself are performed.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_LINE_TACTICS',				'Gunpowder has become the dominant element of war. We must develop tactics for its most effective use by infantry regiments.'),
		('LOC_BOOST_TRIGGER_LONGDESC_MACHINERY_JNR_6T',				'Surely, craftsmen skilled enough to make complex weapons such as composite bows could build other complex machinery as well.'),
				 ('LOC_BOOST_TRIGGER_MASS_PRODUCTION_JNR_6T',		'Build a Dam.'),
		('LOC_BOOST_TRIGGER_LONGDESC_MASS_PRODUCTION_JNR_6T',		'The construction of this dam has shown that large public works could benefit tremendously from more standardized craftsmanship.'),
				 ('LOC_BOOST_TRIGGER_6T_MECHANICS',					'Earn a Great Engineer.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_MECHANICS',					'Our great engineer is showing us contraptions and devices we have never seen before.'),
				 ('LOC_BOOST_TRIGGER_6T_MEDICINE',					'Have the Natural History civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_MEDICINE',					'A systematic classification of the natural world has proven invaluable in finding new remedies for old ailments.'),
				 ('LOC_BOOST_TRIGGER_6T_METALLURGY',				'Build an Industrial Zone district.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_METALLURGY',				'These new furnaces enable our smiths to create sturdier metals for stronger and sharper blades.'),
				 ('LOC_BOOST_TRIGGER_MILITARY_ENGINEERING_JNR_6T',	'Own 2 Coursers.'),
		('LOC_BOOST_TRIGGER_LONGDESC_MILITARY_ENGINEERING_JNR_6T',	'Now that our supply lines are secured by light cavalry, we should expand the infrastructure of our military logistics.'),
				 ('LOC_BOOST_TRIGGER_MILITARY_SCIENCE_JNR_6T',		'Kill a unit with a Cuirassier.'),
		('LOC_BOOST_TRIGGER_LONGDESC_MILITARY_SCIENCE_JNR_6T',		'Your valiant Cuirassier has vanquished his foe. Let us learn from this victory and become students of military affairs.'),
				 ('LOC_BOOST_TRIGGER_MILITARY_TACTICS_JNR_6T',		'Build a Camp.'),
		('LOC_BOOST_TRIGGER_LONGDESC_MILITARY_TACTICS_JNR_6T',		'Your hunters are skilled marksmen. With the right tactics, they could provide a crucial advantage in battle.'),
				 ('LOC_BOOST_TRIGGER_NUCLEAR_FISSION_JNR_6T',		'Have the Nuclear Program civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_NUCLEAR_FISSION_JNR_6T',		'Research into the fundemental building blocks of all existence has our physicists ponder the effects of breaking their bonds.'),
			   	  ('LOC_BOOST_TRIGGER_6T_OPTICS',					'Build a Lighthouse.'),
		 ('LOC_BOOST_TRIGGER_LONGDESC_6T_OPTICS',					'Your lighthouse guides your ships near shore, but advanced navigation tools could make them more independent when out on the seas.'),
		 ('LOC_BOOST_TRIGGER_LONGDESC_6T_PAPER',					'Controlled flows of water feed and power your population centers, providing the material and power needed to process pulp in ingenious ways.'),
				 ('LOC_BOOST_TRIGGER_6T_PHARMACEUTICALS',			'Grow a city to 25 population.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_PHARMACEUTICALS',			'Your local apothecaries can no longer keep up producing the medicines required to keep your enormous population healthy.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_PHYSICS',					'Joining forces with other nations has started a chain reaction of scientific advances. Will the next push be in physics?'),
				 ('LOC_BOOST_TRIGGER_6T_PIKE_TACTICS',				'Earn a Great General.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_PIKE_TACTICS',				'Our great general thinks that even basic polearms can form the backbone of a powerful army - with the right tactics, of course.'),
				 ('LOC_BOOST_TRIGGER_PLASTICS_JNR_6T',				'Have the Consumerism civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_PLASTICS_JNR_6T',				'Natural materials alone can no longer fulfill your people''s ever-growing desire to consume industrial goods.'),
				 ('LOC_BOOST_TRIGGER_PRINTING_JNR_UC_6T',			'Build 2 Academies.'),
				 ('LOC_BOOST_TRIGGER_RADIO_JNR_6T',					'Earn a Great Musician.'),
		('LOC_BOOST_TRIGGER_LONGDESC_RADIO_JNR_6T',					'Our great musician enchants the senses of anyone with the privilege to listen. How can we share this experience with the whole country?'),
				 ('LOC_BOOST_TRIGGER_6T_REFRIGERATION',				'Have the Professional Sports civic.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_REFRIGERATION',				'The masses attending sports events all over the country would enjoy it even more with a cold beverage in their hands.'),
				 ('LOC_BOOST_TRIGGER_6T_REFRIGERATION_BREWERY',		'Build a Brewery.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_REFRIGERATION_BREWERY',		'Refreshing beverages are in high demand, but only few places can keep them cool throughout the summer. Technical solutions are desired.'),
				 ('LOC_BOOST_TRIGGER_REPLACEABLE_PARTS_JNR_6T',		'Own 3 Line Infantry units.'),
		('LOC_BOOST_TRIGGER_LONGDESC_TECH_RIFLING_JNR_6T',			'Beholding the power of the musket in action, an idea springs to mind that an accurate firearm would spell the doom of all other weapons.'),
				 ('LOC_BOOST_TRIGGER_ROCKETRY_JNR_6T',				'Build 2 Oil Power Plants.'),
		('LOC_BOOST_TRIGGER_LONGDESC_ROCKETRY_JNR_6T',				'Harnessing the power of more and more advanced fuels, we might soon be able to travel beyond this planet itself.'),
				 ('LOC_BOOST_TRIGGER_6T_SADDLE',					'Kill a unit with a Horseman.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_SADDLE',					'Your horsemen could thrust their weapons much better if they were seated more securely on the back of their horse.'),
				 ('LOC_BOOST_TRIGGER_SATELLITES_JNR_UC',			'Complete Launch Earth Satellite project.'),
		('LOC_BOOST_TRIGGER_LONGDESC_SATELLITES_JNR_UC',			'A prototype satellite has been launched succesfully and your experts are already working on more specialized systems.'),
				 ('LOC_BOOST_TRIGGER_6T_SIEGE_ENGINES',				'Own 2 Catapults.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_SIEGE_ENGINES',				'Hurling rocks at walls is working out well so far. With more advanced engines we could launch 90kg projectiles at targets over 300m away.'),
				 ('LOC_BOOST_TRIGGER_6T_SPINNING_WHEEL',			'Build 3 Water Mills.'),
				 ('LOC_BOOST_TRIGGER_6T_SPINNING_WHEEL_JNR_UC',		'Build 2 Water Mills.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_SPINNING_WHEEL',			'Your Water Mills could be a great boon to the textiles industry.'),
		('LOC_BOOST_TRIGGER_LONGDESC_SQUARE_RIGGING_JNR_6T',		'Our shipyards are building ships bigger than ever before, but new rigging techniques are required to sail them effectively.'),
				 ('LOC_BOOST_TRIGGER_STEALTH_TECHNOLOGY_JNR_6T',	'Own 2 Nuclear Submarines.'),
		('LOC_BOOST_TRIGGER_LONGDESC_STEALTH_TECHNOLOGY_JNR_6T',	'The threat potential of our nuclear forces could be even greater if we were able to shield them from electronic detection.'),
				 ('LOC_BOOST_TRIGGER_STEAM_POWER_JNR_6T',			'Own 2 Frigates.'),
		('LOC_BOOST_TRIGGER_LONGDESC_STEAM_POWER_JNR_6T',			'How much larger can sailing vessels become? Our engineers are experimenting with using steam power to propel transports instead.'),
				 ('LOC_BOOST_TRIGGER_STEEL_JNR_6T',					'Build a Coal Mine.'),
		('LOC_BOOST_TRIGGER_LONGDESC_STEEL_JNR_6T',					'With coal as fuel, our furnaces can achieve higher temperatures and our iron can be made even stronger.'),
		('LOC_BOOST_TRIGGER_LONGDESC_STIRRUPS_JNR_6T',				'The feudal lords seek to build impressive defenses to protect our their holdings.'),	
				 ('LOC_BOOST_TRIGGER_6T_SURVEYING',					'Build a Plantation.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_SURVEYING',					'Our planters are staking claims on the most fertile soils. We need to measure our lands and document it to solve any upcoming disputes.'),
				 ('LOC_BOOST_TRIGGER_SYNTHETIC_MATERIALS_JNR_6T',	'Build 2 Hangars.'),
		('LOC_BOOST_TRIGGER_LONGDESC_SYNTHETIC_MATERIALS_JNR_6T',	'Our aeronautical engineers are constantly experimenting with new materials to make aircraft even lighter.'),
				 ('LOC_BOOST_TRIGGER_6T_WARPLANES',					'Build an Aerodrome district.'),
		('LOC_BOOST_TRIGGER_LONGDESC_6T_WARPLANES',					'We have conquered the skies. Time to use it to our advantage in battle.'),
		('LOC_BOOST_TRIGGER_LONGDESC_THE_WHEEL_JNR_6T',				'A farmer discovers that laying logs under his load allows it to be transported more easily when pulled by sturdy cattle.');
--------------------------------------------------------------