INSERT OR REPLACE INTO LocalizedText
		(Tag,								Language,		Text)
VALUES	("LOC_CITY_NAME_THEBES",			"en_US",		"Waset"),
		("LOC_CITY_NAME_MEMPHIS",			"en_US",		"Men-Nefer"),
		("LOC_CITY_NAME_RA_KEDET",			"en_US",		"Râ-Kedet"),
		("LOC_CITY_NAME_IWNW",				"en_US",		"Iunu"),
		("LOC_CITY_NAME_ABYDOS",			"en_US",		"Abdju"),
		("LOC_CITY_NAME_PER_BAST",			"en_US",		"Per-Bast"),
		("LOC_CITY_NAME_KHMUN",				"en_US",		"Khemenu"),
		("LOC_CITY_NAME_NEKHEN",			"en_US",		"Nekhen"),
		("LOC_CITY_NAME_SHEDET",			"en_US",		"Phiom"),
		("LOC_CITY_NAME_PER_RAMESSES",		"en_US",		"Per-Ramesses"),
		("LOC_CITY_NAME_AKHETATEN",			"en_US",		"Akhetaten"),
		("LOC_CITY_NAME_THIS",				"en_US",		"Thinis"),
		("LOC_CITY_NAME_NUBT",				"en_US",		"Nubt"),
		("LOC_CITY_NAME_HUT_WARET",			"en_US",		"Hut-Waret"),
		("LOC_CITY_NAME_ITJTAWY",			"en_US",		"Itjtawy"),
		("LOC_CITY_NAME_BUSIRIS",			"en_US",		"Djedu"),
		("LOC_CITY_NAME_TJEBNUTJER",		"en_US",		"Tjebnutjer"),
		("LOC_CITY_NAME_BUTO",				"en_US",		"Per-Wadjet"),
		("LOC_CITY_NAME_MENDES",			"en_US",		"Djedet"),
		("LOC_CITY_NAME_THONIS",			"en_US",		"Thonis"),
		("LOC_CITY_NAME_DJANET",			"en_US",		"Djanet"),
		("LOC_CITY_NAME_SENA",				"en_US",		"Per-Amun"),
		("LOC_CITY_NAME_IUNET",				"en_US",		"Iunet"),
		("LOC_CITY_NAME_TAREMU",			"en_US",		"Taremu"),
		("LOC_CITY_NAME_TA_SENET",			"en_US",		"Ta-Senet"),
		("LOC_CITY_NAME_PEGUAT",			"en_US",		"Peguat");