-- ('', '', 'de_DE'),


INSERT OR REPLACE INTO LocalizedText
(Tag, Text, Language) VALUES

('LOC_POLICY_SCRIPTURE_DESCRIPTION', '+100 % Nachbarschaftsboni der Heiligen Stätte. (Details zum Pantheon in der Zivilopädie ansehen)' , 'de_DE'),
('LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_SCRIPTURE_CHAPTER_HISTORY_PARA_1', '***Olympische Pantheons***[NEWLINE]Diese Richtlinie gilt für die Glaubensboni von:[NEWLINE]Alpheus[NEWLINE]Aphrodite (nur Heilige Stätte)[NEWLINE]Gaia[NEWLINE]Helios[NEWLINE]Hestia[NEWLINE]Pan[NEWLINE]Persephone[NEWLINE]Poseidon[NEWLINE]Zeus (nur Heilige Stätte)[NEWLINE][NEWLINE]Diese Richtlinie gilt nicht für Glaubensboni von:[NEWLINE]Apollo[NEWLINE]Ares[NEWLINE]Artemis[NEWLINE]Athena[NEWLINE]Atlas[NEWLINE]Demeter[NEWLINE]Dionysos[NEWLINE]Hades[NEWLINE]Hephaistos[NEWLINE]Hera' , 'de_DE'),
('LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_SCRIPTURE_CHAPTER_HISTORY_PARA_2', 'Der älteste bisher gefundene religiöse Text stammt aus dem alten Sumer um 2600 v. Chr. Es war das erste Beispiel einer Schrift, ein Text, der als heilig oder zentral für eine religiöse Tradition gilt. Der älteste einer noch existierenden Religion ist wahrscheinlich das Rigveda des Hinduismus, komponiert zwischen 1700 und 1100 v Die fünf größten existierenden Religionen haben alle eine Hauptschrift: Buddhismus (Tripitaka), Hinduismus (Veden und Upanishaden), Islam (Quran), Judentum (Tanach) und Christentum (Bibel).' , 'de_DE'),

('LOC_OP_ALPHEUS', 'Alpheus', 'de_DE'),
('LOC_OP_ALPHEUS_DESCRIPTION', 'Fluss --> [ICON_Gold][NEWLINE](+1 Gold durch Flusskacheln)[NEWLINE]Bezirke der Heiligen Stätte erhalten +5 [ICON_Faith] Glaube von einem angrenzenden Fluss', 'de_DE'),
('LOC_OP_DISTRICT_RIVER_FAITH', '+{1_num} [ICON_Faith] Glaube von Alpheus', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ALPHEUS_CHAPTER_HISTORY_PARA_1', 'Alpheus war ein Fluss (der moderne Fluss Alfeios) und ein Flussgott. Wie die meisten Flussgötter ist er ein Sohn von Okeanos und Tethys. Telegone, die Tochter von Pharis, gebar seinen Sohn, den König Orsilochus. Durch ihn , Alpheus war der Großvater von Diokles und Urgroßvater eines Soldatenpaares, Krethon und Orsilochus, die während des Trojanischen Krieges von Aeneas getötet wurden. Alpheus war auch der Fluss, den Herakles in der fünften seiner Arbeiten der Reihe nach umleitete den Augiasstall an einem einzigen Tag vom Dreck zu befreien, eine Aufgabe, die man für unmöglich gehalten hatte.', 'de_DE'),


('LOC_OP_APHRODITE', 'Aphrodite', 'de_DE'),
('LOC_OP_APHRODITE_DESCRIPTION', 'Atemberaubend --> [ICON_Faith][ICON_Faith][NEWLINE](+2 Glaube durch Kacheln mit atemberaubender Anziehungskraft)[NEWLINE]Distrikte mit atemberaubender Anziehungskraft erhalten +2 [ICON_Faith] Glaube', 'de_DE'),
('LOC_OP_DISTRICT_APPEAL_FAITH', '+{1_num} [ICON_Faith] Glaube von Aphrodite', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_APHRODITE_CHAPTER_HISTORY_PARA_1', 'Aphrodite ist eine Göttin, die mit Liebe, Schönheit, Vergnügen und Zeugung in Verbindung gebracht wird. In Hesiods Theogonie wird Aphrodite vor der Küste von Cythera aus dem Schaum geboren, der von Uranus Genitalien produziert wird, die sein Sohn Kronos wurde abgetrennt und ins Meer geworfen. In Homers Ilias ist sie jedoch die Tochter von Zeus und Dione.[NEWLINE][NEWLINE]Aphrodite war mit Hephaistos, dem Gott der Schmiede und der Metallverarbeitung, verheiratet war ihm häufig untreu und hatte viele Liebhaber; in der Odyssee wird sie beim Ehebruch mit dem Kriegsgott Ares erwischt.', 'en_US'),

('LOC_OP_APOLLO', 'Apollo', 'de_DE'),
('LOC_OP_APOLLO_DESCRIPTION', 'Weiden --> [ICON_Production][ICON_Culture][ICON_Culture][NEWLINE](+1 Produktion und +2 Kultur durch Weiden)[NEWLINE]Weiden erhalten +5 [ICON_Faith] Glauben, wenn sie neben einer heiligen Stätte stehen [NEWLINE]Das Orakel erhält +5 [ICON_Faith] Faith', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_APOLLO_CHAPTER_HISTORY_PARA_1', 'Apollo ist eine der wichtigsten und komplexesten olympischen Gottheiten. Das Ideal des Kouros (eines bartlosen, athletischen Jünglings), Apollo wurde verschiedentlich als Gott der Musik, Wahrheit und Prophezeiung, Heilung, Sonne und Licht, Seuche, Poesie usw. Apollo ist der Sohn von Zeus und Leto und hat eine Zwillingsschwester, die keusche Jägerin Artemis.[NEWLINE][NEWLINE]Unter anderem ist er der Schutzpatron der Herden und Herden. Er ist auch mit der Fruchtbarkeit von Rindern verbunden.', 'de_DE'),

('LOC_OP_ARES', 'Ares', 'de_DE'),
('LOC_OP_ARES_DESCRIPTION', 'Keine Kriegsmüdigkeit[NEWLINE]Landmilitäreinheiten in fremdem Territorium:[NEWLINE][ICON_Bullet]+6[ICON_STRENGTH]/[ICON_Ranged]/[ICON_Bombard] beim Angriff[NEWLINE][ICON_Bullet]Kills geben dir [ICON_Faith] gleich der Basis der besiegten Einheit [ICON_STRENGTH][NEWLINE]Heilige Stätten neben einem Lager erhalten +10 [ICON_Faith] Faith', 'de_DE'),
('LOC_OP_ABILITY_ARES_FOREIGN_STRENGTH_NAME', 'Ares: Fremde Stärke', 'de_DE'),
('LOC_OP_ABILITY_ARES_FOREIGN_STRENGTH_DESCRIPTION', 'Landmilitäreinheiten in fremdem Territorium: +6[ICON_STRENGTH]/[ICON_Ranged]/[ICON_Bombard] beim Angriff', 'de_DE'),
('LOC_OP_ARES_FOREIGN_STRENGTH_COMBAT_DESCRIPTION', '+{1_Value} Ares', 'de_DE'),
('LOC_OP_ABILITY_ARES_FAITH_ON_KILL_NAME', 'Ares: Faith on Kill', 'de_DE'),
('LOC_OP_ABILITY_ARES_FAITH_ON_KILL_DESCRIPTION', 'Landmilitäreinheiten in fremdem Territorium: Kills geben dir [ICON_Faith] entsprechend der Basis der besiegten Einheit', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ARES_CHAPTER_HISTORY_PARA_1', 'Ares ist der Gott des Krieges; Sohn von Zeus und Hera. In der griechischen Literatur repräsentiert er oft den physischen oder gewalttätigen und ungezähmten Aspekt des Krieges, im Gegensatz zu seiner Schwester, der gepanzerten Athene, die als ein Göttin der Intelligenz gehören militärische Strategie und Generalität.[NEWLINE][NEWLINE]Die Griechen standen Ares ambivalent gegenüber: Obwohl er die körperliche Tapferkeit verkörperte, die für den Erfolg im Krieg notwendig ist, war er eine gefährliche Kraft, "überwältigend, unersättlich im Kampf, zerstörerisch und Menschenmord."', 'de_DE'),


('LOC_OP_ARTEMIS', 'Artemis', 'de_DE'),
('LOC_OP_ARTEMIS_DESCRIPTION', 'Lager --> [ICON_Food][ICON_Food][ICON_Production][ICON_Gold][NEWLINE](+2 Nahrung, +1 Produktion und +1 Gold aus Lagern)[NEWLINE]Lager erhalten +5 [ICON_Faith] Glaube neben einer heiligen Stätte[NEWLINE]Der Tempel der Artemis erhält +5 [ICON_Faith] Glaube', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ARTEMIS_CHAPTER_HISTORY_PARA_1', 'Artemis war die Tochter von Zeus und Leto und die Zwillingsschwester von Apollo. Sie war die Göttin der Jagd, der wilden Tiere, der Wildnis, der Geburt, der Jungfräulichkeit und der Beschützerin junger Mädchen, die Frauen Krankheiten brachte und linderte ; oft wurde sie als Jägerin mit Pfeil und Bogen dargestellt. Der Hirsch und die Zypresse waren ihr heilig.', 'de_DE'),

('LOC_OP_ATHENA', 'Athena', 'de_DE'),
('LOC_OP_ATHENA_DESCRIPTION', '[ICON_RESOURCE_BANANAS][ICON_RESOURCE_CITRUS][ICON_RESOURCE_COTTON][ICON_RESOURCE_DYES][ICON_RESOURCE_OLIVES][ICON_RESOURCE_SILK][ICON_RESOURCE_SUGAR] --> [ICON_Production][ICON_Science][ICON_Science][NEWLINE](+1 Produktion und aus Bananen-, Zitrus-, Baumwoll-, Farbstoff-, Oliven-, Seiden- und Zuckerplantagen)[NEWLINE]Diese erhalten auch +5 [ICON_Faith] Glaube neben einer heiligen Stätte', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ATHENA_CHAPTER_HISTORY_PARA_1', 'Athena ist eine Göttin, die mit Weisheit, Handwerk, Weberei und Kriegsführung in Verbindung gebracht wird. Sie war auch eine Kriegergöttin und es wurde angenommen, dass sie Soldaten in die Schlacht führte. Athena war auch die Schutzgöttin des heroischen Strebens; sie half Perseus, Herakles, Bellerophon und Jason bei ihren Abenteuern.[NEWLINE][NEWLINE]Athena wurde aus dem Kopf ihres Vaters Zeus geboren und galt seit der Renaissance als Beschützerin verschiedener Städte in ganz Griechenland (insbesondere der Stadt Athen). ist zu einem internationalen Symbol für Weisheit, Kunst und klassisches Lernen geworden. Westliche Künstler und Allegoriker haben die Athene oft als Symbol für Freiheit und Demokratie verwendet.', 'de_DE'),

('LOC_OP_ATLAS', 'Atlas', 'de_DE'),
('LOC_OP_ATLAS_DESCRIPTION', 'Steinbrüche --> [ICON_Production][ICON_Production][ICON_Faith][NEWLINE](+2 Produktion und +1 Glaube aus Steinbrüchen)[NEWLINE]Steinbrüche erhalten +4 [ICON_Faith] Glaube, wenn sie sich neben einer heiligen Stätte befinden ', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ATLAS_CHAPTER_HISTORY_PARA_1', 'Atlas war ein Titan, der dazu verdammt war, den Himmel für die Ewigkeit zu halten. Obwohl er mit verschiedenen Orten in Verbindung gebracht wurde, wurde er allgemein mit dem Atlasgebirge in Nordwestafrika (dem heutigen Marokko, Algerien und Tunesien) identifiziert. Atlas war der Sohn des Titanen Iapetus und der Ozeaniden Asia oder Clymene. Er hatte viele Kinder, meist Töchter, die Hesperiden, die Hyaden, die Plejaden und die Nymphe Calypso, die auf der Insel Ogygia lebte. Atlas stand am Ende der Erde in Richtung der West. ''Atlantic Ocean'' bedeutet ''Atlasmeer'', während ''Atlantis'' ''Insel des Atlas'' bedeutet.', 'de_DE'),

('LOC_OP_DEMETER', 'Demeter', 'de_DE'),
('LOC_OP_DEMETER_DESCRIPTION', 'Farmen --> [ICON_Food][NEWLINE](+1 Nahrung von Farmen, einschließlich Terrassenfarmen)[NEWLINE]Farmen erhalten +3 [ICON_Faith] Glaube neben einer heiligen Stätte', 'de_DE') ,
('LOC_PEDIA_RELIGIONS_PAGE_OP_DEMETER_CHAPTER_HISTORY_PARA_1', 'Demeter ist die Göttin des Getreides, der Landwirtschaft, der Ernte, des Wachstums und der Ernährung, die über das Getreide und die Fruchtbarkeit der Erde herrschte. Obwohl Demeter oft einfach als die Göttin der Ernte beschrieben wird, präsidierte sie auch über das heilige Gesetz und den Kreislauf von Leben und Tod.', 'de_DE'),

('LOC_OP_DIONYSUS', 'Dionysus', 'de_DE'),
('LOC_OP_DIONYSUS_DESCRIPTION', '[ICON_RESOURCE_COCOA][ICON_RESOURCE_COFFEE][ICON_RESOURCE_INCENSE][ICON_RESOURCE_SPICES][ICON_RESOURCE_TEA][ICON_RESOURCE_TOBACCO][ICON_RESOURCE_WINE] --> [Icon_Amenities][Icon_Amenities][Icon_Amenities](+100) diese Stadt aus Plantagen auf Kakao-, Kaffee-, Weihrauch-, Gewürz-, Tee-, Tabak- und Weinplantagen)[NEWLINE]Diese erhalten auch +5 [ICON_Faith] Glaube neben einer heiligen Stätte', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_DIONYSUS_CHAPTER_HISTORY_PARA_1', 'Dionysos ist der Gott der Weinlese, der Weinherstellung und des Weins, der Fruchtbarkeit, des rituellen Wahnsinns, der religiösen Ekstase und des Theaters. Er ist ein Sohn des Zeus und der sterblichen Semele, also halbgöttlich oder heroisch. Wein spielte eine wichtige Rolle in der griechischen Kultur, und der Kult des Dionysos stellte den religiösen Hauptfokus für seinen hemmungslosen Konsum dar. Er ist eine bedeutende, populäre Figur der griechischen Mythologie und Religion und in einigen Listen der zwölf Olympioniken als letzter enthalten ihrer Zahl, und der einzige Gott, der von einer sterblichen Mutter geboren wurde.[NEWLINE][NEWLINE]Dionysos wird von den Stadtreligionen als Beschützer derer repräsentiert, die nicht der konventionellen Gesellschaft angehören, und er symbolisiert somit das Chaotische, Gefährliche und Unerwartete, alles was der menschlichen Vernunft entgeht und nur dem unvorhersehbaren Handeln der Götter zuzuschreiben ist.Als Eleutherios ("der Befreier") befreien sein Wein, seine Musik und sein ekstatischer Tanz seine Anhänger von selbstbewusster Angst und Fürsorge und unterwandert die erdrückenden Beschränkungen der Mächtigen. Diejenigen, die an seinen Mysterien teilhaben, sind vom Gott selbst besessen und ermächtigt. Seine Festivals waren die treibende Kraft hinter der Entwicklung des griechischen Theaters.', 'de_DE'),

('LOC_OP_GAIA', 'Gaia', 'de_DE'),
('LOC_OP_GAIA_DESCRIPTION', 'Regenwald --> [ICON_Food][NEWLINE](+1 Nahrung von Regenwaldplättchen)[NEWLINE]Gebiete der Heiligen Stätte erhalten +2 [ICON_Faith] Glaube von angrenzenden Regenwaldplättchen', 'de_DE'),
('LOC_OP_DISTRICT_JUNGLE_FAITH', '+{1_num} [ICON_Faith] Faith from Gaia', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_GAIA_CHAPTER_HISTORY_PARA_1', 'Gaia ist die Verkörperung der Erde und eine der griechischen Urgottheiten. Gaia ist die Ahnenmutter allen Lebens: die Urgöttin Mutter Erde. Sie ist die unmittelbare Mutter von Uranus (dem Himmel), von dessen sexuelle Vereinigung gebar sie die Titanen (selbst Eltern vieler der olympischen Götter) und die Riesen und Pontus (das Meer), aus dessen Vereinigung sie die ursprünglichen Meeresgötter gebar. Ihr Äquivalent im römischen Pantheon war Terra.', ' de_DE'),

('LOC_OP_HADES', 'Hades', 'de_DE'),
('LOC_OP_HADES_DESCRIPTION', 'Luxus-/Bonusminen --> [ICON_Production][ICON_Gold][ICON_Gold][ICON_Gold][ICON_Gold][ICON_Gold][NEWLINE](+1 Produktion und +5 Gold aus Minen über Luxus- und Bonusressourcen) [NEWLINE]Diese Minen erhalten +5 [ICON_Faith] Glaube neben einer heiligen Stätte', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HADES_CHAPTER_HISTORY_PARA_1', 'Hades war der chthonische Gott der Unterwelt, der schließlich seinen Namen annahm. Er war der älteste Sohn von Cronus und Rhea, obwohl der letzte Sohn von seinem Vater erbrochen wurde. Er und seine Brüder Zeus und Poseidon besiegten ihren Vater Hades erhielt die Unterwelt, Zeus den Himmel und Poseidon das Meer, wobei allen drei gleichzeitig die feste Erde zur Verfügung stand.[NEWLINE][NEWLINE]Vielleicht aus Angst, seinen Namen auszusprechen, fingen die Griechen um das 5. Jahrhundert v. Chr. an, Hades als Pluto zu bezeichnen, dessen Wurzel „reich“ bedeutet, wenn man bedenkt, dass Reichtümer aus dem Untergrund kommen ( z. B. fruchtbare Ernten, Edelmetalle usw.) Ausgefeiltere Namen der gleichen Gattung waren Ploutodotes oder Ploutodoter, was „Geber des Reichtums“ bedeutet.', ' de_DE'),

('LOC_OP_HELIOS', 'Helios', 'de_DE'),
('LOC_OP_HELIOS_DESCRIPTION', 'Desert --> [ICON_FOOD][ICON_PRODUCTION][ICON_FAITH][ICON_Gold][NEWLINE](+1 Food, +1 Production, +1 Faith, and +1 Gold from Desert tiles that do not have an Oasis or Floodplains)[NEWLINE]Holy Site districts get +1 [ICON_Faith] Faith from adjacent Desert tiles[NEWLINE]The Colossus gets +5 [ICON_Faith] Faith', 'de_DE'),
('LOC_OP_DISTRICT_DESERT_FAITH', '+{1_num} [ICON_Faith] Faith from Helios', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HELIOS_CHAPTER_HISTORY_PARA_1', 'Helios ist der Gott der Sonne. Er ist der Sohn des Titanen Hyperion und der Titanin Theia und Bruder der Göttinnen Selene, des Mondes, und Eos, der Morgenröte.[NEWLINE][NEWLINE]Helios ist ein hübscher Jüngling, gekrönt mit dem strahlenden Sonnenkranz, der jeden Tag den Sonnenwagen über den Himmel zum erdumkreisenden Okeanos lenkte und nachts durch den Weltozean nach Osten zurückkehrte.', 'de_DE'),

('LOC_OP_HEPHAESTUS', 'Hephaestus', 'de_DE'),

('LOC_OP_HEPHAESTUS_DESCRIPTION', 'Strategische Minen --> [ICON_Production][ICON_Science][ICON_Culture][ICON_Faith][ICON_Gold][NEWLINE](+1 Produktion, +1 Wissenschaft, +1 Kultur, +1 Glaube und +1 Gold von Minen über strategische Ressourcen)[NEWLINE]Diese Minen erhalten +5 [ICON_Faith] Glaube, wenn sie sich neben einer heiligen Stätte befinden', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HEPHAESTUS_CHAPTER_HISTORY_PARA_1', 'Hephaestus ist der griechische Gott der Schmiede, der Metallverarbeitung, der Zimmerleute, Handwerker, Kunsthandwerker, Bildhauer, der Metallurgie, des Feuers und der Vulkane. Hephaistos war entweder der Sohn von Zeus und Hera oder er war Heras parthenogenes Kind, wegen seiner Missbildung von seiner Mutter verstoßen und vom Olymp auf die Erde geworfen.[NEWLINE][NEWLINE]Als Schmiedegott stellte Hephaistos alle Waffen der Götter im Olymp her.Er diente als Schmied der Götter und wurde in den Produktions- und Industriezentren Griechenlands, insbesondere in Athen, verehrt.', 'de_DE'),

('LOC_OP_HERA', 'Hera', 'de_DE'),
('LOC_OP_HERA_DESCRIPTION', 'Immer loyal[NEWLINE](Deine Städte sind immun gegen Loyalitätsdruck)[NEWLINE]Heilige Stätten erhalten +3/7/12/18/25/33 [ICON_Faith] Glauben basierend auf der Anzahl der Gouverneurstitel der Gouverneur der Stadt hat', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HERA_CHAPTER_HISTORY_PARA_1', 'Hera ist die Göttin der Frauen, der Ehe, der Familie und der Geburt, eine der Zwölf Olympionikinnen und die Schwesterfrau des Zeus. Sie ist die Tochter der Titanen Cronus und Rhea. Hera regiert über den Olymp als Königin der Götter. Als matronenhafte Figur diente Hera sowohl als Schutzpatronin als auch als Beschützerin verheirateter Frauen, leitete Hochzeiten und segnete eheliche Verbindungen. Eines der charakteristischen Merkmale von Hera ist ihre eifersüchtige und rachsüchtige Natur gegenüber Zeus zahlreichen Liebhabern und uneheliche Nachkommen, sowie die Sterblichen, die sie kreuzen. Doch sie verlässt Zeus nie...', 'de_DE'),

('LOC_OP_HERMES', 'Hermes', 'de_DE'),
('LOC_OP_HERMES_DESCRIPTION', 'Roads --> Free to capital, Faster // Harvest --> [ICON_Faith][NEWLINE](Ihre Städte in Handelsroutenreichweite haben automatisch eine Straße zu Ihrer Hauptstadt. Straßen in Ihrem Territorium sind eine Ebene höher fortgeschrittener als üblich (z. B. klassisch statt antik).[NEWLINE]Das Ernten einer Ressource oder das Entfernen eines Features erhält [ICON_Faith] Faith in Höhe der Menge des anderen Ertrags.)', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HERMES_CHAPTER_HISTORY_PARA_1', 'Hermes ist der Gott des Handels, der Heraldik, der Kaufleute, des Handels, der Straßen, des Sports, der Reisenden und der Athleten; der Sohn des Zeus und der Plejade Maia, er war der zweitjüngste der olympischen Götter (Dionysos ist der der Jüngste).[NEWLINE][NEWLINE]Hermes war der Abgesandte und Bote der Götter, der göttliche ''Trickster'' und der Gott der Grenzen und der Grenzüberschreitung, der Patron der Hirten, Diebe, Gräber und Herolde. Er soll sich frei zwischen den Welten der Sterblichen und der Göttlichen bewegen und war der Leiter der Seelen ins Jenseits. Er galt auch als Beschützer und Schutzpatron der Straßen und Reisenden.', 'de_DE'),

('LOC_OP_HESTIA', 'Hestia', 'de_DE'),
('LOC_OP_HESTIA_DESCRIPTION', 'Wald --> [ICON_Gold][NEWLINE](+1 Gold von Waldplättchen)[NEWLINE]Gebiete der Heiligen Stätte erhalten +1 [ICON_Faith] Glaube von angrenzenden Waldplättchen', 'de_DE'),
('LOC_OP_DISTRICT_FOREST_FAITH', '+{1_num} [ICON_Faith] Glaube aus Hestia', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HESTIA_CHAPTER_HISTORY_PARA_1', 'Hestia ist eine jungfräuliche Göttin des Herdes, der Architektur und der richtigen Ordnung der Häuslichkeit, der Familie, des Hauses und des Staates. Sie ist eine Tochter von Kronos und Rhea. Hestia erhielt immer das erste Opfer Opfer im Haushalt. Der Herd des Prytaneums fungierte als ihr offizielles Heiligtum. Mit der Gründung einer neuen Kolonie würde die Flamme von Hestias öffentlichem Herd in der Mutterstadt in die neue Siedlung getragen werden.', 'de_DE') ,

('LOC_OP_PAN', 'Pan', 'de_DE'),
('LOC_OP_PAN_DESCRIPTION', 'Reeds --> [ICON_Culture][ICON_Culture][NEWLINE](+2 Culture from Marsh, Oasis, and Floodplain tiles)[NEWLINE]Holy Site districts get +2 [ICON_Faith] Faith from adjacent Marsh, Oasis, and Floodplain tiles', 'de_DE'),
('LOC_OP_DISTRICT_REEDS_FAITH', '+{1_num} [ICON_Faith] Faith from Pan', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_PAN_CHAPTER_HISTORY_PARA_1', 'Pan ist der Gott der Wildnis, der Hirten und Herden, der Natur der Bergwildnis, der rustikalen Musik und Improvisation und der Begleiter der Nymphen. Er hat die Hinterhand, die Beine und die Hörner einer Ziege in demselben Art als Faun oder Satyr. Mit seiner Heimat im ländlichen Arkadien wird er auch als Gott der Felder, Haine, bewaldeten Täler anerkannt und oft mit Sex in Verbindung gebracht; aus diesem Grund wird Pan mit Fruchtbarkeit und der Jahreszeit des Frühlings in Verbindung gebracht Die alten Griechen betrachteten Pan auch als den Gott der Theaterkritik.[NEWLINE][NEWLINE]Die Panflöte ist nach Pan benannt. Syrinx, eine Waldnymphe, versuchte, der Zuneigung des Gottes Pan zu entkommen und verwandelte sich in ein Schilfrohr , Pan schnitt mehrere Rohre zurecht, legte sie parallel nebeneinander, band sie zusammen und fertigte daraus ein melodisches Musikinstrument.Die alten Griechen nannten dieses Instrument Syrinx, zu Ehren der Muse, und Pandean, oder Panflöte und Panflöte. Flöte, nach Pan. Die Syrinx, ein Pre vorherrschend pastorales Instrument für die Griechen, wurde von den Etruskern übernommen, die es bei ihren Festen und Banketten spielten; die Etrusker nannten es Fistel. Die Römer übernahmen die Syrinx von den Griechen und Etruskern, und auch sie spielten sie bei ihren Banketten, Festen sowie bei religiösen und Trauerprozessionen.', 'de_DE'),

('LOC_OP_PERSEPHONE', 'Persephone', 'de_DE'),
('LOC_OP_PERSEPHONE_DESCRIPTION', 'Tundra & Schnee --> [ICON_Food][ICON_PRODUCTION][ICON_Faith] [NEWLINE](+1 Nahrung, +1 Produktion und +1 Glaube aus Tundra- und Schneekacheln)[NEWLINE]Bezirke der Heiligen Stätte erhalten +1 [ICON_Faith] Glaube von angrenzenden Tundra- und Schneeplättchen', 'de_DE'),
('LOC_OP_DISTRICT_SNOW_OR_TUNDRA_FAITH', '+{1_num} [ICON_Faith] Glaube von Persephone', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_PERSEPHONE_CHAPTER_HISTORY_PARA_1', 'Persephone ist die Tochter von Zeus und Demeter. Homer klar sie als die beeindruckende, ehrwürdige, majestätische Prinzessin der Unterwelt, die die Flüche der Menschen auf die Seelen der Toten wirkt. Sie wurde die Königin der Unterwelt durch ihre Entführung durch und anschließende Heirat mit Hades, dem Gott der Unterwelt. Ihre Entführung ist die Personifikation des Winters, der sich jedes Jahr nach der Ernte zurückzieht.', 'de_DE'),

('LOC_OP_POSEIDON', 'Poseidon', 'de_DE'),
('LOC_OP_POSEIDON_DESCRIPTION', 'Ocean --> [ICON_Production][ICON_Production][ICON_Production][ICON_Faith] // Pferde --> [ICON_Faith][NEWLINE](+3 Produktion und +1 Glaube auf Ozeankacheln. +1 Glaube auf Pferdeplättchen)[NEWLINE]Gebiete der Heiligen Stätte erhalten +2 [ICON_Faith] Glaube von angrenzenden Küsten-/Ozeanplättchen', 'de_DE'),
('LOC_OP_DISTRICT_WATER_FAITH', '+{1_num} [ICON_Faith] Glaube von Poseidon', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_POSEIDON_CHAPTER_HISTORY_PARA_1', 'Poseidon war Gott des Meeres und anderer Gewässer, der Erdbeben und der Pferde. Poseidon war Beschützer der Seefahrer und vieler Städte und Kolonien. In Homers Ilias unterstützt Poseidon die Griechen gegen die Trojaner während des Trojanischen Krieges In der Odyssee, während der Seereise von Troja zurück nach Ithaka, provoziert der griechische Held Odysseus Poseidons Wut, indem er seinen Sohn, den Zyklopen, blendet, was dazu führt, dass Poseidon ihn mit Stürmen bestraft, der vollständige Verlust von sein Schiff und seine Gefährten und eine Verzögerung von zehn Jahren. Die Insel Atlantis war Poseidons Domäne.', 'de_DE'),

('LOC_OP_ZEUS', 'Zeus', 'de_DE'),
('LOC_OP_ZEUS_DESCRIPTION', 'Berge --> +1 Nachbarschaft zu Bezirken[NEWLINE](Berge bieten einen +1 Nachbarschaftsbonus für Flugplätze[ICON_Production], Aquädukte[ICON_Food], Campus[ICON_Science], Handelszentren[ICON_Gold], Lager[ICON_Production], Unterhaltungskomplexe[ICON_Culture], Häfen[ICON_Gold], Heilige Stätten[ICON_Faith], Industriezonen[ICON_Production], Nachbarschaften[ICON_Faith], Theaterplätze[ICON_Culture] und Wasserparks[ICON_Science])[NEWLINE]Die Statue des Zeus bekommt +5 [ICON_Faith] Glaube', 'de_DE'),
('LOC_OP_DISTRICT_MOUNTAIN_PRODUCTION', '+{1_num} [ICON_Production] Produktion von Zeus', 'de_DE'),
('LOC_OP_DISTRICT_MOUNTAIN_SCIENCE', '+{1_num} [ICON_Science] Wissenschaft von Zeus', 'de_DE'),
('LOC_OP_DISTRICT_MOUNTAIN_CULTURE', '+{1_num} [ICON_Culture] Kultur von Zeus', 'de_DE'),
('LOC_OP_DISTRICT_MOUNTAIN_FAITH', '+{1_num} [ICON_Faith] Glaube von Zeus', 'de_DE'),
('LOC_OP_DISTRICT_MOUNTAIN_FOOD', '+{1_num} [ICON_Food] Nahrung von Zeus', 'de_DE'),
('LOC_OP_DISTRICT_MOUNTAIN_GOLD', '+{1_num} [ICON_Gold] Gold von Zeus', 'de_DE'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ZEUS_CHAPTER_HISTORY_PARA_1', 'Zeus ist der Himmels- und Donnergott, der als König der Götter des Olymp regiert. Zeus ist das Kind von Cronus und Rhea, dem jüngsten seiner geborenen Geschwister, obwohl er manchmal als der älteste angesehen wird andere mussten aus Cronus Magen ausgespuckt werden.[NEWLINE][NEWLINE]Er ist mit Hera verheiratet, von der er angeblich Ares, Hebe und Hephaistos gezeugt hat Dione, von der er Aphrodite zeugte, Zeus war auch berüchtigt für seine erotischen Eskapaden, die zu vielen göttlichen und heldenhaften Nachkommen führten, darunter Athene, Apollo, Artemis, Hermes, Persephone, Dionysos, Perseus, Herakles, Helena von Troja, Minos und andere die Musen.', 'de_DE') ;
