-- UC_ENT_Text
-- Author: JNR
-- Translation: Gorowynn
--------------------------------------------------------------

-- German
--------------------------------------------------------------
INSERT OR REPLACE INTO LocalizedText
		(Tag, 														Language, 	Text,																								Gender, 		Plurality	) VALUES
		('LOC_BUILDING_JNR_TOURNEY_NAME',							'de_DE',	'Turnierplatz|Turnierplatz|Turnierplatz|Turnierplatzes|Turnierplatz', 								'masculine', 	1			),
		('LOC_BUILDING_JNR_BOTANICAL_GARDEN_NAME',					'de_DE',	'Botanischer Garten|Botanischen Garten|Botanischen Garten|Botanischen Gartens|Botanische Garten', 	'masculine', 	1			),
		('LOC_BUILDING_JNR_THEME_PARK_NAME',						'de_DE',	'Kongresszentrum|Kongresszentrum|Kongresszentrum|Kongresszentrums|Kongresszentrum', 				'neuter', 		1			),
		('LOC_BUILDING_JNR_MARINA_NAME',							'de_DE',	'Yachthafen|Yachthafen|Yachthafen|Yachthafens|Yachthafen', 											'masculine', 	1			),
		('LOC_BUILDING_JNR_CASINO_NAME',							'de_DE',	'Kasino|Kasino|Kasino|Kasinos|Kasino', 																'neuter', 		1			),
		('LOC_BUILDING_JNR_MARITIME_MUSEUM_NAME',					'de_DE',	'Meereskundemuseum|Meereskundemuseum|Meereskundemuseum|Meereskundemuseums|Meereskundemuseum', 		'neuter', 		1			),
		('LOC_BUILDING_JNR_FOOD_COURT_NAME',						'de_DE',	'Konzerthalle|Konzerthalle|Konzerthalle|Konzerthalle|Konzerthalle', 								'feminine', 	1			),
		('LOC_YIELD_JNR_DUMMY_ADJACENCYTOURISM_NAME',				'de_DE',	'Tourismus|Tourismus|Tourismus|Tourismus|Tourismus', 												'masculine', 	1			),
		('LOC_POLICY_JNR_HASTILUDE_NAME',							'de_DE',	'Hastiludia|Hastiludia|Hastiludia|Hastiludia|Hastiludia', 											'feminine', 	1			),
		('LOC_POLICY_JNR_STATE_FAIRS_NAME',							'de_DE',	'Landesausstellung|Landesausstellung|Landesausstellung|Landesausstellung|Landesausstellung', 		'feminine', 	1			),
		('LOC_POLICY_JNR_RED_LIST_NAME',							'de_DE',	'Rote Liste|Roten Liste|Roten Liste|Roten Liste|Rote Liste', 										'feminine', 	1			);

INSERT OR REPLACE INTO LocalizedText
		(Tag,															Language,	Text)
VALUES	('LOC_BUILDING_ARENA_DESCRIPTION_UC_JNR',						'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten, wenn diese Stadt einen etablierten Gouverneur hat. Turnierplätze innerhalb von 6 Feldern um das Stadtzentrum geben keinen weiteren Bonus.'),
		('LOC_BUILDING_JNR_TOURNEY_DESCRIPTION',						'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Feldern ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Turnierplätze oder Arenen innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_Tourism] Tourismus für jeden Verbündeten, der eine Handelsroute zu dieser Stadt hat.'),
		('LOC_BUILDING_TLACHTLI_DESCRIPTION_UC_JNR',					'de_DE',	'Ein einzigartiges Gebäude der Azteken, welches die Arena sowie den Turnierplatz ersetzt.[NEWLINE]Liefert +1 [ICON_Amenities] Annehmlichkeit und zusätzlich +1 [ICON_Amenities] Annehmlichkeit wenn im Krieg. +1 [ICON_Culture] Kultur und +1 [ICON_GreatGeneral] Großer-General-Punkt. +1 [ICON_FAITH] Glauben für jede ursprüngliche Hauptstadt einer Zivilisation im Besitz.'),
		('LOC_BUILDING_ZOO_DESCRIPTION_UC_JNR',							'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Feldern ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Botanische Gärten innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_Science] Wissenschaft für jedes Ressourcenfeld mit Weide oder Lager innerhalb dieser Stadt.'),
		('LOC_BUILDING_JNR_BOTANICAL_GARDEN_DESCRIPTION',				'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Feldern ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Zoos innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_Science] Wissenschaft für jedes Ressourcenfeld mit Bauernhof, Plantage oder Sägewerk innerhalb dieser Stadt.[NEWLINE]+2 [ICON_Tourism] Tourismus.'),
		('LOC_BUILDING_THERMAL_BATH_DESCRIPTION_UC_JNR',				'de_DE',	'Ein einzigartiges Gebäude Ungarns, welches den Zoo und den Botanischen Garten ersetzt.[NEWLINE]+1 [ICON_AMENITIES] Annehmlichkeit und +2 [ICON_PRODUCTION] Produktion, ausgeweitet auf jedes Stadtzentrum innerhalb von 6 Feldern. Dieser Bonus zählt nur einfach pro Stadt und weitere Thermalbäder innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]Diese Stadt erhält +2 [ICON_SCIENCE] Wissenschaft, [ICON_CULTURE] Kultur, [ICON_TOURISM] Tourismus und weitere [ICON_AMENITIES] Annehmlichkeiten, wenn sich mindestens ein geothermaler Riss innerhalb der Stadtgrenzen befindet.'),
		('LOC_BUILDING_STADIUM_DESCRIPTION_UC_JNR',						'de_DE',	'+1 [ICON_Amenities] Annehmlichkeit für je 4 Spezialbezirke in dieser Stadt oder für je 2 Spezialbezirke in dieser Stadt, wenn mit Strom versorgt.[NEWLINE]+1 [ICON_GOLD] Gold für jedes Stadion oder Schwimmbad, wenn mit Strom versorgt.[NEWLINE]+2 [ICON_Tourism] Tourismus, wenn die [ICON_CITIZEN] Stadtbevölkerung mindestens 10 beträgt und +5 [ICON_Tourism] Tourismus, wenn [ICON_CITIZEN] 20 oder höher.'),
		('LOC_BUILDING_JNR_THEME_PARK_DESCRIPTION',						'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 9 Felder ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Kongresszentren innerhalb von 9 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+100% Nachbarschaftsbonus des Unterhaltungskomplexes dieser Stadt.'),
		('LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION_UC_JNR',				'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Felder ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Riesenräder innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_Tourism] Tourismus.'),
		('LOC_BUILDING_JNR_MARINA_DESCRIPTION',							'de_DE',	'+1 [ICON_Amenities] Annehmlichkeit für jedes Fischerboot angrenzend an diesen Bezirk.[NEWLINE]+1 [ICON_CULTURE] Kultur und +1 [ICON_Tourism] Tourismus für jedes Fischerboot der Stadt.'),
		('LOC_BUILDING_AQUARIUM_DESCRIPTION_UC_JNR',					'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Felder ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Aquarien oder Kasinos innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_SCIENCE] Wissenschaft für jede Küstenressource, Schiffswrack, oder Riff in der Stadt.[NEWLINE]+1 [ICON_Tourism] Tourismus.[NEWLINE]+1 Anziehungskraft für jedes an ein Riff angrenzende Feld in der Stadt.'),
		('LOC_BUILDING_JNR_CASINO_DESCRIPTION',							'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Felder ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Aquarien oder Kasinos innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_GOLD] Gold von jedem Handelszentrum, Hafen, und Flugplatz in dieser Stadt.[NEWLINE]+1 [ICON_Tourism] Tourismus für jedes Wunder in dieser Stadt, das auf oder neben einem Küstenfeld gebaut wurde.'),
		('LOC_BUILDING_JNR_MARITIME_MUSEUM_DESCRIPTION',				'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 6 Felder ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Meereskundemuseen oder Kasinos innerhalb von 6 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+1 [ICON_GOLD] Gold von jedem Hafen, Arsenal und Hafenviertel in dieser Stadt.[NEWLINE]+1 [ICON_Tourism] Tourismus für jedes Wunder in dieser Stadt, das auf oder neben einem Küstenfeld gebaut wurde.'),
		('LOC_BUILDING_AQUATICS_CENTER_DESCRIPTION_UC_JNR',				'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten für je 4 Spezialbezirke in dieser Stadt oder für je 2 Spezialbezirke, wenn mit Strom versorgt.[NEWLINE]+1 [ICON_GOLD] Gold von jedem Stadion oder Schwimmbad, wenn mit Strom versorgt.[NEWLINE]+2 [ICON_Tourism] Tourismus wenn die [ICON_CITIZEN] Stadtbevölkerung mindestens 10 beträgt und +5 [ICON_Tourism] Tourismus wenn [ICON_CITIZEN] 20 oder höher.'),
		('LOC_BUILDING_JNR_FOOD_COURT_DESCRIPTION',						'de_DE',	'Zusätzliche [ICON_Amenities] Annehmlichkeiten werden auf weitere Stadtzentren innerhalb von 9 Felder ausgeweitet. Dieser Bonus zählt nur einfach pro Stadt und weitere Konzerthallen innerhalb von 9 Feldern gewähren keinen weiteren Bonus.[NEWLINE]+100% Nachbarschaftsbonus des Wasserparks in dieser Stadt.'),
		('LOC_DISTRICT_TOURISM_JNR_DESCRIPTION',						'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Bezirk; other?n Bezirken;}.'),
		('LOC_GOVERNMENT_TOURISM_JNR_DESCRIPTION',						'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Regierungsbezirk; other?n Regierungsbezirken;}.'),
		('LOC_THEATER_TOURISM_JNR_DESCRIPTION',							'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Theaterplatz; other?n Theaterplätzen;}.'),
		('LOC_COMMERCIAL_HUB_TOURISM_JNR_DESCRIPTION',					'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Handelszentrum; other?n Handelszentren;}.'),
		('LOC_HARBOR_TOURISM_JNR_DESCRIPTION',							'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Hafen; other?n Häfen;}.'),
		('LOC_GEOTHERMAL_TOURISM_JNR_DESCRIPTION',						'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m geothermalen Riss; other?n geothermalen Rissen;}.'),
		('LOC_REEF_TOURISM_JNR_DESCRIPTION',							'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Riff; other?n Riffen;}.'),
		('LOC_SKI_RESORT_TOURISM_JNR_DESCRIPTION',						'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Ski-Resort; other?n Ski-Resorts;}.'),
		('LOC_BEACH_RESORT_TOURISM_JNR_DESCRIPTION',					'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Strand-Resort; other?n Strand-Resorts;}.'),
		('LOC_WONDER_TOURISM_JNR_DESCRIPTION',							'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Wunder; other?n Wundern;}.'),
		('LOC_GOLF_COURSE_TOURISM_JNR_DESCRIPTION',						'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Golfplatz; other?n Golfplätzen;}.'),
		('LOC_ICE_HOCKEY_RINK_TOURISM_JNR_DESCRIPTION',					'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Eishockeystadium; other?n Eishockeystadien;}.'),
		('LOC_BATEY_TOURISM_JNR_DESCRIPTION',							'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Batey; other?n Bateys;}.'),
		('LOC_DISTRICT_ACROPOLIS_TOURISM_JNR_DESCRIPTION',				'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) vom angrenzende{1_num : plural 1?r Akropolis; other?n Akropolis-Bezirken;}.'),
		('LOC_DISTRICT_SUGUBA_TOURISM_JNR_DESCRIPTION',					'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) vom angrenzende{1_num : plural 1?r Suguba; other?n Sugubas;}.'),
		('LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_TOURISM_JNR_DESCRIPTION',	'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) vom angrenzende{1_num : plural 1?m Royal-Navy-Dock; other?n Royal-Navy-Docks;}.'),
		('LOC_DISTRICT_COTHON_TOURISM_JNR_DESCRIPTION',					'de_DE',	'+{1_num} [ICON_GOLD] Gold (und [ICON_TOURISM] Tourismus wenn Luftfahrt erforscht) von angrenzende{1_num : plural 1?m Cothon; other?n Cothonen;}.'),
		('LOC_DISTRICT_ACROPOLIS_DESCRIPTION_JNR_UC_ENT',				'de_DE',	'Ein einzigartiger Bezirk der Griechen. Ersetzt den Theaterplatz und ist einfacher zu bauen. Verleiht 1 [ICON_Envoy] Gesandten bei Fertigstellung.[NEWLINE][NEWLINE]+1 [ICON_Culture] für jeden angrenzenden Bezirk, sowie zusätzlich +1 [ICON_Culture] Kultur für jedes angrenzende Stadtzentrum, Unterhaltungskomplex, oder Wasserpark. +2 [ICON_Culture] Kultur für jedes angrenzende Wunder. Kann nur auf Hügeln gebaut werden.'),
		('LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION_JNR_UC',			'de_DE',	'Erlaubt dem Handwerker ein Eishockeystadion zu bauen.[NEWLINE][NEWLINE]+1 [ICON_AMENITIES] Annehmlichkeit. +1 [ICON_CULTURE] Kultur für jedes angrenzende Tundra-, Tundrahügel-, Schnee- und Schneehügel-Feld. Liefert [ICON_Tourism] Tourismus durch Kultur sobald Luftfahrt erforscht wurde. +2 [ICON_FOOD] Nahrung und [ICON_PRODUCTION] Produktion sobald Profisport freigeschaltet wurde. +4 [ICON_CULTURE] Kultur wenn angrenzend an einen Stufe 3 Unterhaltungskomplex oder Wasserpark. Kann nur auf Tundra, Tundrahügeln, Schnee und Schneehügeln gebaut werden. 1x pro Stadt. +2 Anziehungskraft.'),
		('LOC_POLICY_JNR_HASTILUDE_DESCRIPTION',						'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten und +1 [ICON_Gold] Gold Nachbarschaftsbonus in Unterhaltungskomplexen und Wasserparks.'),
		('LOC_POLICY_SPORTS_MEDIA_DESCRIPTION_JNR_UC',					'de_DE',	'+100% Nachbarschaftsbonus des Theaterplatzes. Stadien und Schwimmbäder generieren +1 [ICON_Amenities] Annehmlickeit.'),
		('LOC_POLICY_JNR_STATE_FAIRS_DESCRIPTION',						'de_DE',	'+100% Nachbarschaftsbonus des Unterhaltungskomplexes und Wasserparks. Kongresszentren und Konzerthallen generieren +1 [ICON_Amenities] Annehmlichkeit.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION',							'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten durch Zoos, Botanische Gärten und Aquarien. Gleiche Anzahl an [ICON_SCIENCE] Wissenschaft, wenn der Bezirk mindestens +4 Nachbarschaftsbonus bietet. Gleiche Anzahl an [ICON_CULTURE] Kultur, wenn die [ICON_CITIZEN] Bevölkerung der Stadt 15 oder höher ist.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION_MMSS',					'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten durch Zoos, Botanische Gärten und Aquarien. Gleiche Anzahl an [ICON_SCIENCE] Wissenschaft, wenn der Bezirk mindestens +4 Nachbarschaftsbonus bietet. Gleiche Anzahl an [ICON_CULTURE] Kultur, wenn die [ICON_CITIZEN] Bevölkerung der Stadt 15 oder höher ist.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION_PRESERVE',				'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten durch Zoos, Botanische Gärten und Aquarien. Gleiche Anzahl an [ICON_SCIENCE] Wissenschaft, wenn die Stadt ein Schutzgebiet besitzt. Gleiche Anzahl an [ICON_CULTURE] Kultur, wenn der Bezirk mindestens +4 Nachbarschaftsbonus bietet.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION_PRESERVE_MMSS',			'de_DE',	'+1 [ICON_Amenities] Annehmlichkeiten durch Zoos, Botanische Gärten und Aquarien. Gleiche Anzahl an [ICON_SCIENCE] Wissenschaft, wenn die Stadt ein Schutzgebiet besitzt. Gleiche Anzahl an [ICON_CULTURE] Kultur, wenn der Bezirk mindestens +4 Nachbarschaftsbonus bietet.');

UPDATE LocalizedText SET Text=Text || '[NEWLINE]Liefert [ICON_TOURISM] Tourismus entsprechend dem [ICON_GOLD] Goldbonus, sobald Luftfahrt erforscht wurde.' WHERE Language='de_DE' AND Tag='LOC_DISTRICT_ENTERTAINMENT_COMPLEX_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Liefert [ICON_TOURISM] Tourismus entsprechend dem [ICON_GOLD] Goldbonus, sobald Luftfahrt erforscht wurde.' WHERE Language='de_DE' AND Tag='LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Liefert [ICON_TOURISM] Tourismus entsprechend dem [ICON_GOLD] Goldbonus, sobald Luftfahrt erforscht wurde.' WHERE Language='de_DE' AND Tag='LOC_DISTRICT_STREET_CARNIVAL_EXPANSION2_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Liefert [ICON_TOURISM] Tourismus entsprechend dem [ICON_GOLD] Goldbonus, sobald Luftfahrt erforscht wurde.' WHERE Language='de_DE' AND Tag='LOC_DISTRICT_WATER_STREET_CARNIVAL_EXPANSION2_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Liefert [ICON_TOURISM] Tourismus entsprechend dem [ICON_GOLD] Goldbonus, sobald Luftfahrt erforscht wurde.' WHERE Language='de_DE' AND Tag='LOC_DISTRICT_HIPPODROME_EXPANSION2_DESCRIPTION';
--------------------------------------------------------------
