-- BOOM_ASSYRIA_TEXT
-- Author: Boom
-- DateCreated: 4/24/2022 7:10:09 PM
--------------------------------------------------------------
INSERT INTO EnglishText
--ability text
		(Tag,																							'Text')
VALUES	('LOC_CIVILIZATION_BOOM_ASSYRIA_NAME',															'Assyria'																																																																																																																														),
		('LOC_CIVILIZATION_BOOM_ASSYRIA_DESCRIPTION',													'Assyrian Empire'																																																																																																																												),
		('LOC_CIVILIZATION_BOOM_ASSYRIA_ADJECTIVE',														'Assyrian'																																																																																																																														),
		('LOC_LEADER_BOOM_ASHURBANIPAL_NAME',															'Ashurbanipal'																																																																																																																													),
		('LOC_TRAIT_LEADER_BOOM_ASHURBANIPAL_NAME',														'Treasures of Ninevah'																																																																																																																											),
		('LOC_TRAIT_LEADER_BOOM_ASHURBANIPAL_DESCRIPTION',												'Great Works of [ICON_GreatWork_Writing] Writing provide +1 [ICON_Science] Science and [ICON_Culture] Culture, with an additional +1 [ICON_Science] Science and [ICON_Culture] Culture for each Campus building present in the city. Conquering a city grants a burst of [ICON_GreatWriter] Great Writer points. Earning a [ICON_GreatWriter] Great Writer grants a free [ICON_TechBoosted] Eureka. Gain the Library of Ashurbanipal unique building in the Government Plaza'													),
		('LOC_TRAIT_CIVILIZATION_BOOM_ASSYRIA_NAME',													'Ruba''Um'																																																																																																																														),
		('LOC_TRAIT_CIVILIZATION_BOOM_ASSYRIA_DESCRIPTION',												'+25% [ICON_Production] Production in founded cities toward military and support units. +35% [ICON_Production] Production in conquered cities toward districts and buildings that already exist in the [ICON_Capital] Capital. Gain access to the Mass Resettlement project.'																																																													),
		('LOC_BOOM_IMPROVEMENT_LAMASSU_NAME',															'Lamassu'																																																																																																																														),
		('LOC_BOOM_IMPROVEMENT_LAMASSU_DESCRIPTION',													'Unlocks the builder ability to construct a Lamassu, unique to Assyria.[NEWLINE][NEWLINE]+2 [ICON_Faith] Faith. Adjacent City Center provides +1 [ICON_Food] Food and [ICON_Production] Production if built in a founded city, or +1 [ICON_Science] and +1 [ICON_Culture] if built in a conquered city. +1 [ICON_Science] Science and [ICON_Faith] Faith for each adjacent Campus. +1 [ICON_Culture] Culture and [ICON_Faith] Faith for each adjacent Theater Square. Additional [ICON_Science] Science and [ICON_Tourism] Tourism as you advance through the Technology and Civic Trees. May only be built on flat tiles.'	),
		('LOC_BOOM_UNIT_SIEGE_ENGINE_NAME',																'Siege Engine'																																																																																																																													),
		('LOC_BOOM_UNIT_SIEGE_ENGINE_DESCRIPTION',														'Assyrian unique unit that replaces the Battering Ram. This unit has extra movement, and allows attacking Melee and Anti-Cavalry units to ignore walls and immediately assault the city. Adjacent units gain +5 [ICON_Strength] Strength against fortifications and +8 [ICON_Strength] Strength when defending against ranged attacks.'																																															),
		('LOC_PROJECT_BOOM_MASS_RESETTLEMENT_NAME',														'Mass Resettlement'																																																																																																																												),
		('LOC_PROJECT_BOOM_MASS_RESETTLEMENT_DESCRIPTION',												'When complete, this project transfers one [ICON_Citizen] Population from all captured cities within a 5 tile radius to this city. Grants free Roads around the city.'																																																																																							),
		('LOC_BOOM_ASSYRIA_UNIT_SIEGE_BONUS_DESCRIPTION',												'+5 [ICON_Strength] Combat Strength against defensible districts from Siege Engine'																																																																																																												),
		('LOC_BOOM_ASSYRIA_UNIT_DEFENSE_BONUS_DESCRIPTION',												'+8 [ICON_Strength] Combat Strength when defending against Ranged Attacks from Siege Engine'																																																																																																									),
		('LOC_BUILDING_BOOM_ROYAL_LIBRARY_NAME',														'Library of Ashurbanipal'																																																																																																																										),
		('LOC_BUILDING_BOOM_ROYAL_LIBRARY_DESCRIPTION',													'A building unique to Assyria. This building provides 5 slots for Great Works of [ICON_GreatWork_Writing] Writing and may be themed.[NEWLINE]Awards +1 [ICON_Governor] Governor Title.'																																																																																			),
		('LOC_AGENDA_BOOM_ERUDITE_NAME',																'Erudite'),
		('LOC_AGENDA_BOOM_ERUDITE_DESCRIPTION',															'Likes civilizations who are less advanced than him. Dislikes civilizations who are more advanced than him or compete with him for Great Works of [ICON_GreatWork_Writing] Writing.'),
		('LOC_DIPLO_KUDO_EXIT_LEADER_BOOM_ASHURBANIPAL_ANY',											'You understand that the strength and intelligence bestowed on me by the grace of gods is insurmountable. This is good.'),
		('LOC_DIPLO_KUDO_LEADER_BOOM_ASHURBANIPAL_REASON_ANY',											'(You are less advanced in science in culture)'),
		('LOC_DIPLO_MODIFIER_BOOM_ERUDITE_LAGGING',														'You are weird'),	
		('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',						'Very well. I shall bestow upon your people the wisdom and strength of Assyria.'),
		('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',						'Your presumption in acting as my equal astounds me. Pray that I do not take it as an insult'),
		('LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',								'I offer you the cooperation of Assyria. Join me in the graces of Ashur!'),
		('LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',						'Very good, we stand as equals.'),
		('LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',						'You would turn aside my generosity?'),
		('LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',								'For this insolence, I will crush your people and grind your cities to dust.'),
		('LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',									'Ashur has granted me the strength and wisdom to raze your empire to the ground and make your people and knowledge my own.'),
		('LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',							'Your delegation shall return to you filled with wonder at the sights of Assyria and the splendor of the Royal Library.'),
		('LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',							'Your filthy savage people shall not even deign to approach the wonders of the Assyrian Empire.'),
		('LOC_DIPLO_DELEGATION_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',									'Assyria sends you kipteh and dokhwa, prepared by our royal chefs.'),
		('LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',									'Your slander of me displays your woeful ignorance. Your foolish words mean nothing.'),
		('LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',										'Your incompetence at ruling is exceeded only by your malice and stupidity. I seek only to destroy you. (Denounces You).'),
		('LOC_DIPLO_FIRST_MEET_LEADER_BOOM_ASHURBANIPAL_ANY',											'I am Ashurbanipal, king of the universe, whom the gods have bestowed with intelligence and strength. Are you afraid?'),
		('LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_BOOM_ASHURBANIPAL_ANY',							'Assyria has prepared a glorious reception for you, shall you come see our capital?'),
		('LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_BOOM_ASHURBANIPAL_ANY',					'Of course.'),
		('LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_BOOM_ASHURBANIPAL_ANY',						'I shall tell you of the great city of Ninevah and its grand library, if you will tell me of your cities.'),
		('LOC_DIPLO_GREETING_LEADER_BOOM_ASHURBANIPAL_ANY',												'Greetings again.'),
		('LOC_DIPLO_WARNING_EXIT_LEADER_BOOM_ASHURBANIPAL',												'You would attempt to match the wisdom bestowed upon me by the gods? You are even more foolish than I assumed.'),
		('LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',								'Let us make an accord to unravel the secrets of the universe together.'),
		('LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_BOOM_ASHURBANIPAL_ANY',							'Assyria has taken what she requires from you. Let peace be had.'),
		('LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_BOOM_ASHURBANIPAL_ANY',							'This war shall not end until your people are corpses and your cities are dust.'),
		('LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',									'Assyria is prepared to grant you mercy, if you would make peace.'),
		('LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',						'Very well, you may move through the lands of Ashur.'),
		('LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_BOOM_ASHURBANIPAL_ANY',						'Your people shall not enter the lands of Ashur,'),
		('LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',									'My armies have conquests to make, may we cross your land?'),
		('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_BOOM_ASHURBANIPAL_ANY',						'Move your troops from my border at once, unless you wish to feel the full force of the Assyrian Empire'),
		('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_BOOM_ASHURBANIPAL_ANY',	'No. My troop movements are necessary, you would not understand.'),
		('LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_BOOM_ASHURBANIPAL_ANY',	'Very well, Assyria shall withdraw, for now.'),
		('LOC_DIPLO_DEFEAT_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',										'With cries of woe I bring my days to an end. On the day of the city god, the day of the festival, I am wretched; death is seizing hold upon me, and bears me down...'),
		('LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',								'This offer is an insult.'),
		('LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_BOOM_ASHURBANIPAL_ANY',								'Very well, this offer serves us both.'),
		('LOC_CIVINFO_BOOM_ASSYRIA_LOCATION',															'Middle East'),
		('LOC_CIVINFO_BOOM_ASSYRIA_SIZE',																'650,000 square miles (1.6 million square km)'),
		('LOC_CIVINFO_BOOM_ASSYRIA_POPULATION',															'Approximately 5 million at its peak'),
		('LOC_CIVINFO_BOOM_ASSYRIA_CAPITAL',															'Capital varied from ruler to ruler, kings often moved their capital.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_ASHURBANIPAL_QUOTE',											'I reduced the temples of Elam to naught; their gods and goddesses I scattered to the winds. The tombs of their ancient and recent kings I devastated, I exposed to the sun, and I carried away their bones toward the land of Ashur. I devastated the provinces of Elam and on their lands I sowed salt.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_CAPSULE_BODY',						'Ashurbanipal seeks to conquer nearby cities in order to gain new knowledge through the Great Writer points he earns and the accumulation of Great Works of Writing he receives.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_DETAILED_BODY',						'As the largest and most powerful empire of the ancient Mesopotamian world, known for their strength in siegecraft and incorporating captured empires under their control, Assyria is able to quickly take down cities with the Siege Engine unit, and quickly make them productive with their bonus to infrastructure in those cities. Ashurbanipal utilizes Assyria''s powerful conquest abilities in order to recruit [ICON_GreatWriter] Great Writers, which then allow him to leap ahead in the Technology and Civics trees'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_1',						'Ashurbanipal was born in 685BC, the fourth son to the Assyrian king Esarhaddon, and thus seemed destined to never become king, with three others in the line of succession before him. However, in 674BC, the unexpected death of Esarhaddon''s eldest son threw the Assyrian court into chaos. Wishing to cement his succession, Esarheddon proclaimed his second son, Shamash-shum-ukin, the king of Babylon, and Ashurbanipal as the king of Assyria. This unexpected compromise allowed Ashurbanipal to rise to the head of Assyria in 669, during which time he cooperated with his sibling as "equal brothers" in ruling.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_2',						'Despite some fears of rebellion during his ascension to the throne, especially by his grandmother, who forced the lords of Assyria to swear fealty to Ashurbanipal, the change of power was peaceful. Shamash-shum-ukin was crowned a year later, but despite the wishes of their father that they remain "equal brothers", Ashurbanipal intentionally drew power toward himself, demanding an oath of fealty from his brother. This grab at power foreshadowed the events of his rule'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_3',						'With his power consolidated in the Assyrian heartland, Ashurbanipal swiftly set about bringing the rest of the empire under his firm control. Two rebellions came with the death of Esarheddon, in Egypt and Elam. Ashurbanipal, who had been fighting political intrigue, had not opposed them, but once he had gathered his strength, he swiftly put down both rebellions, taking back the cities which had been lost to the rebels and sacking them as punishment. Following this, a series of additional rebellions popped up. Ashurbanipal crushed them with a ruthless efficiency for which he would become infamous, and even marched into the Elam homeland, which had supported the rebellion, and killed all their supporters.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_4',						'At this point, Shamash-shum-ukin had been chafing extensively under Ashurbanipal''s iron fist. Although he supposedly was king of all of Babylonia, in reality he only controlled Babylon and some of the surrounding territory. With growing dissatisfaction toward the balance of power and Ashurbanipal''s poor treatment of him, Shamash-shum-ukin revolted in 652BC, seeking Babylonian independence under his own rule. His resistance was strengthened by the discontent of other conquered peoples in the Assyrian Empire, who supported his rebellion.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_5',						'Despite his many allies, Shamash-shum-ukin was unable to halt Ashurbanipal''s advances. By 650BC, the Assyrian armies had reached the gates of Babylon itself, kicking off a siege that lasted two years. When the city finally fell, Ashurbanipal once again demonstrated his cruelty, killing thousands of citizens of the city, desecrating their corpses, pillaging their treasures, and starting a fire that ravaged the city. Shamash-shum-ukin is also believed to have died in this fire. Ashurbanipal appointed a vassal king in his place.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_6',						'Following the defeat of his brother, Ashurbanipal embarked on several more campaigns throughout the Middle East and Asia. He began with the Elamites, who had supported Shamash-shum-ukin during the rebellion. The Elamite kings were weak and could not stand up to Ashurbanipal''s threats, and when he invaded Elam he utterly crushed their civilization, desecrating their tombs, looting holy relics, and razed their cities to the ground. All the Elamite people he carried away as workmen or slaves and their former vassals he made his own. Following this victory, Ashurbanipal also made a series of incursions into Arabic lands, which although did not result in captured territory, did net him huge amounts of plunder.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_7',						'Although Ashurbanipal was characteristically cruel and brutal toward his enemies, he was well-loved by his people, and much of the loot he obtained from his campaigns was spent in public works projects or other works toward scientific or cultural advancement. He is known for his patronage of artists, and art produced under his rule is characteristically different from art from other rulers.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_8',						'Ashurbanipal''s crowning achievement was the Library of Ashurbanipal. Ashurbanipal believed himself strong in both body and mind, and as such, he created the first universal library, which became the largest library in the world at the time, and for long after, unsurpassed until the Library of Alexandria. The library was filled with texts both Assyrian in origin and many others taken from the conquered empires that Ashurbanipal had subjugated, as such, it was a momentous undertaking, and widely known in the ancient Mesopotamian world.'),
		('LOC_PEDIA_LEADERS_PAGE_LEADER_BOOM_ASHURBANIPAL_CHAPTER_HISTORY_PARA_9',						'Despite Ashurbanipal''s demonstrations of military prowess and advancements in Assyrian power and culture, he was unable to hold the empire together. The death of Shamash-shum-ukin kicked off massive unrest in the Assyrian empire, due to the death of a member of the Assyrian royal family and the damage done to a huge part of the Assyrian Empire. By the time of Ashurbanipal''s death in 631BC, internal political strife and numerous rebellions had reduced the Assyrian Empire to a shadow of its former self, and with his death the empire crumbled completely.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_1',				'Assyria began as a city under the control of the empire of neo-Sumeria in the 21st century BC. It became an independent city-state briefly, but its status as a trade center and lack of military strength made it a target of conquest, and possession of the city changed several times over the next few centuries. Finally, in the 14th century BC, the Assyrians'' latest ruler, the kingdom of Mitanni, collapsed, leaving them as an independent state once again under the rule of Ashur-uballit I.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_2',				'With the fall of Mitanni, many territories near Assyrian land became ripe for conquest. Taking advantage of this, many of the early Assyrian kings led campaigns into said territory. Thus, this period in Assyrian history, known as Middle Assyria, was marked by significant expansion and even defeats of other major empires. Notably, the Assyrians defeated the Hittites at the battle of Nihriya in 1237BC, and even briefly conquered sections of Babylonia.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_3',				'However, following the assassination of Tukulti-Ninurta I, who had destablized Assyria by attemnpting to move the capital away from Assur, the empire''s power fragmented, following kings were unable to hold on to Assyrian territory and the empire constantly grew or shrunk in cycles, as conquests were made by various powerful Assyrian kings, then immediately lost again. The Assyrian decline continued until the ascension of Ashur-dan II in 943BC. Under his rule, the Assyrian decline finally came to an end, and the Neo-Assyrian empire began.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_4',				'With the beginning of the Neo-Assyrian empire, many Assyrian kings were able to make new forays into the land that they were previously unable to hold on to. Particularly important were the conquests of Adad-nirari II, who was not only able to conquer and keep lands far from the Assyrian heartland, but also able to gain the recognition of the Babylonian king at the time, Nabu-shuma-ukin I. The two kings signed a border treaty and were joined through marriage. '),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_5',				'The rise of Assyria continued under Ashurnasirpal II, who was both brutally cruel to those who rebelled against his rule, yet also surprisingly caring of his people, financing a number of building projects, creating water and food reserves, as well as temples, offices, gardens, and various other infrastructure using the plunder from his campaigns. '),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_6',				'Following this period however, the kings of Assyria lost power, and the nobles and magnates of the Assyrian empire wielded much more infleunce. Assyria suffered a number of minor defeats during this period, and was weakened enough to be unable to expand as successfully as it had been able to previously.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_7',				'The ascension and rule of Tiglath-Pileser III marked the end of the power of magnates and the beginning of Assyria''s imperial period. While prior kings focused upon conquest, with little regard to the ruling and beauracracy aspects of running an empire, Tiglath-Pileser III made huge advances in this regard, weakening the magnates, as well as establishing royal governors in newly organized provinces and resettling conquered peoples in order to prevent rebellion. In addition, he also conquered Babylonia, creating the system of two kingships assumed by the ruler of Assyria.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_8',				'Following the death of Tiglath-Pileser, his son Shalmaneser ascended to the throne, but was deposed by Sargon II, who took the throne by force, causing considerable political unrest without Assyria. Due to his fear of retribution from his enemies, Sargon II constructed an entirely new capital, called Dur-Sharrukin, notable for the fact that it was built from the ground up and not an existing city.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_9	',				'After Sargon II''s death in battle, his son Sennacherib reigned, and his reign was relatively uneventful, til the time came for the succession, when his eldest son, Arda-Mulissu, killed him over an argument over the succession. Thus, a younger son of Sennacherib, Esarhaddon, took Ninevah, and was able to force out Arda-Mulissu and take the throne.'),
		('LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_BOOM_ASSYRIA_CHAPTER_HISTORY_PARA_10',				'Although Esarhaddon and his son Ashurbanipal made enormous leaps in governing and conquest, including the capture of Egypt and the building of the Library of Ashurbanipal, the empire had become too large at this point to effectively govern, and various rebellions and internal unrest led to its fall in 622BC, when Ashurbanipal''s young and inexperienced sons lost the Assyrian capital of Ninevah, marking the end of the Assyrian empire.'),
		('LOC_PEDIA_UNITS_PAGE_UNIT_BOOM_SIEGE_ENGINE_CHAPTER_HISTORY_PARA_1',							'The oldest known siege towers date to their use by the armies of the neo-Assyrian Empire c. 9th century BC. Bas-reliefs from the reign of Ashurbanipal II depict siege towers at the walls of enemy towns. At the time, mud-brick walls were generally sufficient protection against the ancient armies of Mesopotamia, but siege towers used by the Assyrians allowed them to overwhelm enemy towns quickly and efficiently, providing their empire with a means to grow virtually unchecked for three centuries.'),
		('LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_BOOM_LAMASSU_CHAPTER_HISTORY_PARA_1',					'The Lamassu originated as a form of worship to the goddess Lama, who was a protective goddess worshipped by the Sumerians. The Assyrians adapted this deity, renaming her to Lamma, and gave her half human, half animal features. Due to the protective power that the goddess was thought to have, sculptures of half human, half winged lions or bulls were placed at the entrances to palaces or other important areas, in order to safeguard what was within'),
		('LOC_PEDIA_BUILDINGS_PAGE_BUILDING_BOOM_ROYAL_LIBRARY_CHAPTER_HISTORY_PARA_1',					'The Library of Ashurbanipal was the greatest, most comprehensive library in the ancient world, unsurpassed until the Library of Alexandria, 400 years later. Despite Ashurbanipal''s fame as commander and brutal conquerer, he was also an intellectual, and as he conquered he also constantly collected various texts from both conquered and his own lands, which he gathered into his library. Some of the most well-known ancient texts today, such as the Epic of Gilgamesh, were found in the library.'),
		('LOC_CITY_NAME_NINEVAH',																		'Ninevah'),
		('LOC_CITY_NAME_ACEMHOYUK',																		'Acemhoyuk'),
		('LOC_CITY_NAME_ARINNU',																		'Arinnu'),
		('LOC_CITY_NAME_ARRAPHA',																		'Arrapha'),
		('LOC_CITY_NAME_ASSUR',																			'Assur'),
		('LOC_CITY_NAME_BAKR_AWA',																		'Bakr-Awa'),
		('LOC_CITY_NAME_BALAWAT',																		'Balawat'),
		('LOC_CITY_NAME_CARCHEMISH',																	'Carchemish'),
		('LOC_CITY_NAME_DEMETRIAS',																		'Demetrias'),
		('LOC_CITY_NAME_DIYARBAKIR',																	'Diyabakir'),
		('LOC_CITY_NAME_DUHOK',																			'Duyok'),
		('LOC_CITY_NAME_ERBIL',																			'Erbil'),
		('LOC_CITY_NAME_GIRD_I_QULRAKH',																'Gird-I Qulrakh'),
		('LOC_CITY_NAME_HALAH',																			'Halah'),
		('LOC_CITY_NAME_HALUS',																			'Halus'),
		('LOC_CITY_NAME_HARRAN',																		'Harran'),
		('LOC_CITY_NAME_IVAH',																			'Ivah'),
		('LOC_CITY_NAME_KAR_TUKULTI_NINURTA',															'Kar-Tukulti-Ninurta'),
		('LOC_CITY_NAME_KELASHIN',																		'Kelashin'),
		('LOC_CITY_NAME_KIRKUK',																		'Kirkuk'),
		('LOC_CITY_NAME_KISHSASSU',																		'Kishsassu'),
		('LOC_CITY_NAME_KOMOPOLIS',																		'Komopolis'),
		('LOC_CITY_NAME_KANESH',																		'Kanesh'),
		('LOC_CITY_NAME_URARTU',																		'Urartu'),
		('LOC_CITY_NAME_NIMRUD',																		'Nimrud'),
		('LOC_CITY_NAME_MARDAMAN',																		'Mardaman'),
		('LOC_CITY_NAME_ALQOSH',																		'Alqosh'),
		('LOC_CITY_NAME_GUZANA',																		'Guzana'),
		('LOC_CITY_NAME_QARQAR',																		'Qarqar'),
		('LOC_CITY_NAME_IMGUR_ENLIL',																	'Imgur-Enlil'),
		('LOC_CITY_NAME_SHUBAT_ENLIL',																	'Shubat-Enlil'),
		('LOC_CITY_NAME_TADMOR',																		'Tadmor'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_1',															'Ammanuel'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_2',															'Shamash'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_3',															'Rabbu'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_4',															'Pirayou'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_5',															'Nukh'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_6',															'Nahro'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_7',															'Moushe'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_8',															'Malkuno'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_9',															'Larsa'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MALE_10',															'Eshai'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_1',															'Bagiyeh'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_2',															'Brula'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_3',															'Doreena'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_4',															'Hazail'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_5',															'Izla'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_6',															'Lawita'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_7',															'Lilis'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_8',															'Lwita'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_9',															'Shahen'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_FEMALE_10',															'Shafira'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_1',														'Seena'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_2',														'Polous'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_3',														'Pirayou'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_4',														'Palakh'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_5',														'Munirsuarta'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_6',														'Luqa'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_7',														'Iskhaq'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_8',														'Gewargis'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_9',														'Gabbara'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_MALE_10',													'Eliyah'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_1',													'Dwura'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_2',													'Damrina'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_3',													'Athra'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_4',													'Arram'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_5',													'Marjanita'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_6',													'Oshana'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_7',													'Rdita'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_8',													'Ninwa'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_9',													'Nahrin'),
		('LOC_CITIZEN_BOOM_ASSYRIAN_MODERN_FEMALE_10',													'Hazail');