-- UC_ENT_Text
-- Author: JNR
--------------------------------------------------------------

-- English
--------------------------------------------------------------
INSERT OR REPLACE INTO EnglishText
		(Tag,															Text)
VALUES	('LOC_BUILDING_ARENA_DESCRIPTION_UC_JNR',						'+1 [ICON_Amenities] Amenity if this city has an established Governor. Tourney Ground buildings within 6 tiles of this city do not provide additional bonuses.'),
		('LOC_BUILDING_JNR_TOURNEY_NAME',								'Tourney Ground'),
		('LOC_BUILDING_JNR_TOURNEY_DESCRIPTION',						'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this or an Arena building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_Tourism] Tourism for every Ally this city has a Trade Route to.'),
		('LOC_BUILDING_TLACHTLI_DESCRIPTION_UC_JNR',					'A building unique to the Aztecs replacing both the Arena and the Tourney Ground.[NEWLINE]Provides 1 [ICON_Amenities] Amenity and an additional +1 [ICON_Amenities] Amenity if at war. +1 [ICON_Culture] Culture and a [ICON_GreatGeneral] Great General Point. +1 [ICON_FAITH] Faith for every original Capital owned.'),
		('LOC_BUILDING_ZOO_DESCRIPTION_UC_JNR',							'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this or a Botanical Garden building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_SCIENCE] Science to each Resource tile in this city with a Pasture or Camp.[NEWLINE]+2 [ICON_Tourism] Tourism.'),
		('LOC_BUILDING_JNR_BOTANICAL_GARDEN_NAME',						'Botanical Garden'),
		('LOC_BUILDING_JNR_BOTANICAL_GARDEN_DESCRIPTION',				'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this or a Zoo building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_SCIENCE] Science to each Resource tile in this city with a Farm, Plantation, or Lumber Mill.[NEWLINE]+2 [ICON_Tourism] Tourism.'),
		('LOC_BUILDING_THERMAL_BATH_DESCRIPTION_UC_JNR',				'A building unique to Hungary replacing both the Zoo and the Botanical Garden.[NEWLINE]+1 [ICON_AMENITIES] Amenity and +2 [ICON_PRODUCTION] Production extend to each city center within 6 tiles. These bonuses apply once to a city, and multiple copies of this building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]This city receives +2 [ICON_SCIENCE] Science, [ICON_CULTURE] Culture, [ICON_TOURISM] Tourism, and additional [ICON_AMENITIES] Amenities if there is at least one Geothermal Fissure in this city''s borders.'),
		('LOC_BUILDING_STADIUM_DESCRIPTION_UC_JNR',						'+1 [ICON_Amenities] Amenity for every 4 Specialty Districts in this city or for every 2 Specialty Districts in this city if powered.[NEWLINE]+1 [ICON_GOLD] Gold from every Stadium and Aquatic Center built if powered.[NEWLINE]+2 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] population is 10 or higher and +5 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] population is 20 or higher.'),
		('LOC_BUILDING_JNR_THEME_PARK_NAME',							'Convention Center'),
		('LOC_BUILDING_JNR_THEME_PARK_DESCRIPTION',						'Bonus [ICON_Amenities] Amenities extend to each city center within 9 tiles. This bonus applies once to a city, and multiple copies of this building within 9 tiles of a city center do not provide additional bonuses.[NEWLINE]Provides Gold equal to this district''s adjacency bonus.'),
		('LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION_UC_JNR',				'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_Tourism] Tourism.'),
		('LOC_BUILDING_JNR_MARINA_NAME',								'Marina'),
		('LOC_BUILDING_JNR_MARINA_DESCRIPTION',							'+1 [ICON_Amenities] Amenity for every Fishing Boats improvement adjacent to this district.[NEWLINE]+1 [ICON_CULTURE] Culture to each Fishing Boats tile in this city.[NEWLINE]+1 [ICON_Tourism] Tourism for every Fishing Boats improvement in this city.'),
		('LOC_BUILDING_AQUARIUM_DESCRIPTION_UC_JNR',					'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this or a Casino building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_SCIENCE] Science to each coastal resource, Shipwreck, and Reef tile in this city.[NEWLINE]+1 [ICON_Tourism] Tourism.[NEWLINE]+1 Appeal to tiles adjacent to Reefs in this city.'),
		('LOC_BUILDING_JNR_CASINO_NAME',								'Casino'),
		('LOC_BUILDING_JNR_CASINO_DESCRIPTION',							'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this or a Aquarium building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_GOLD] Gold from every Commercial Hub, Harbor, and Aerodrome building in this city.[NEWLINE]+1 [ICON_Tourism] Tourism for each Wonder built in this city on or adjacent to a Coast tile.'),
		('LOC_BUILDING_JNR_MARITIME_MUSEUM_NAME',						'Maritime Museum'),
		('LOC_BUILDING_JNR_MARITIME_MUSEUM_DESCRIPTION',				'Bonus [ICON_Amenities] Amenity extends to each city center within 6 tiles. This bonus applies once to a city, and multiple copies of this or a Aquarium building within 6 tiles of a city center do not provide additional bonuses.[NEWLINE]+1 [ICON_GOLD] Gold from every Harbor, Arsenal, and Waterfront building in this city.[NEWLINE]+1 [ICON_Tourism] Tourism for each Wonder built in this city on or adjacent to a Coast tile.'),
		('LOC_BUILDING_AQUATICS_CENTER_DESCRIPTION_UC_JNR',				'+1 [ICON_Amenities] Amenity for every 4 Specialty Districts in this city or for every 2 Specialty Districts in this city if powered.[NEWLINE]+1 [ICON_GOLD] Gold from every Stadium and Aquatic Center built if powered.[NEWLINE]+2 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] population is 10 or higher and +5 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] population is 20 or higher.'),
		('LOC_BUILDING_JNR_FOOD_COURT_NAME',							'Concert Hall'),
		('LOC_BUILDING_JNR_FOOD_COURT_DESCRIPTION',						'Bonus [ICON_Amenities] Amenities extend to each city center within 9 tiles. This bonus applies once to a city, and multiple copies of this building within 9 tiles of a city center do not provide additional bonuses.[NEWLINE]Provides Gold equal to this district''s adjacency bonus.'),
		('LOC_YIELD_JNR_DUMMY_ADJACENCYTOURISM_NAME',					'Tourism'),
		('LOC_DISTRICT_TOURISM_JNR_DESCRIPTION',						'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched) from the adjacent districts.'),
		('LOC_GOVERNMENT_TOURISM_JNR_DESCRIPTION',						'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Government Plaza district.'),
		('LOC_THEATER_TOURISM_JNR_DESCRIPTION',							'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Theater Square district.'),
		('LOC_COMMERCIAL_HUB_TOURISM_JNR_DESCRIPTION',					'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Commercial Hub district.'),
		('LOC_HARBOR_TOURISM_JNR_DESCRIPTION',							'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Harbor district.'),
		('LOC_GEOTHERMAL_TOURISM_JNR_DESCRIPTION',						'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Geothermal Fissure tiles.'),
		('LOC_REEF_TOURISM_JNR_DESCRIPTION',							'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Reef tiles.'),
		('LOC_SKI_RESORT_TOURISM_JNR_DESCRIPTION',						'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Ski {1_Num : plural 1?Resort; other?Resorts;}.'),
		('LOC_BEACH_RESORT_TOURISM_JNR_DESCRIPTION',					'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Seaside {1_Num : plural 1?Resort; other?Resorts;}.'),
		('LOC_WONDER_TOURISM_JNR_DESCRIPTION',							'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent {1_Num : plural 1?wonder; other?wonders;}.'),
		('LOC_GOLF_COURSE_TOURISM_JNR_DESCRIPTION',						'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Golf {1_Num : plural 1?Course; other?Courses;}.'),
		('LOC_ICE_HOCKEY_RINK_TOURISM_JNR_DESCRIPTION',					'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Ice Hockey {1_Num : plural 1?Rink; other?Rinks;}.'),
		('LOC_BATEY_TOURISM_JNR_DESCRIPTION',							'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent {1_Num : plural 1?Batey; other?Bateyes;}.'),
		('LOC_DISTRICT_ACROPOLIS_TOURISM_JNR_DESCRIPTION',				'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Acropolis district.'),
		('LOC_DISTRICT_SUGUBA_TOURISM_JNR_DESCRIPTION',					'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Suguba district.'),
		('LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_TOURISM_JNR_DESCRIPTION',	'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Royal Navy Dockyard district.'),
		('LOC_DISTRICT_COTHON_TOURISM_JNR_DESCRIPTION',					'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent Cothon district.'),
		('LOC_FARM_TOURISM_JNR_DESCRIPTION',							'+{1_num} [ICON_GOLD] Gold (and [ICON_TOURISM] Tourism with Flight researched)from the adjacent {1_Num : plural 1?Farm; other?Farms;}.'),
		('LOC_DISTRICT_ACROPOLIS_DESCRIPTION_JNR_UC_ENT',				'A district unique to Greece for cultural sites. Replaces the Theater Square district and cheaper to build. Awards 1 [ICON_Envoy] Envoy when completed.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture bonus for each adjacent district and an additional +1 [ICON_Culture] Culture bonus for each adjacent City Center, Entertainment Complex, and Water Park. +2 [ICON_Culture] Culture bonus for each adjacent wonder. Can only be built on Hills.'),
		('LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION_JNR_UC',			'Unlocks the Builder ability to construct an Ice Hockey Rink, unique to Canada.[NEWLINE][NEWLINE]+1 [ICON_AMENITIES] Amenity. +1 [ICON_CULTURE] Culture for each adjacent Tundra, Tundra Hills, Snow, and Snow Hills tile. Provides [ICON_Tourism] Tourism from Culture once Flight is unlocked. +2 [ICON_FOOD] Food and [ICON_PRODUCTION] Production once the Professional Sports civic is unlocked. +4 [ICON_CULTURE] Culture if adjacent to a Tier 3 Entertainment Complex or Water Park building. Can be built on Tundra, Tundra Hills, Snow, and Snow Hills. One per city. +2 Appeal.'),
		('LOC_POLICY_JNR_HASTILUDE_NAME',								'Hastilude'),
		('LOC_POLICY_JNR_HASTILUDE_DESCRIPTION',						'+1 [ICON_Amenities] Amenity and +1 [ICON_Gold] Gold adjacency bonus in Entertainment Complexes and Water Parks.'),
		('LOC_POLICY_SPORTS_MEDIA_DESCRIPTION_JNR_UC',					'+100% Theater Square district adjacency bonuses, and Stadiums and Aquatic Centers generate +1 [ICON_Amenities] Amenity.'),
		('LOC_POLICY_JNR_STATE_FAIRS_NAME',								'State Fairs'),
		('LOC_POLICY_JNR_STATE_FAIRS_DESCRIPTION',						'+100% Entertainment Complex and Water Park district adjacency bonuses, and Convention Centers and Concert Halls generate +1 [ICON_Amenities] Amenity.'),
		('LOC_POLICY_JNR_RED_LIST_NAME',								'Red List'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION',							'+1 [ICON_Amenities] Amenity from Zoos, Botanical Gardens, and Aquariums, equal amount of [ICON_SCIENCE] Science if district has at least +4 adjacency bonus, equal amount of [ICON_CULTURE] Culture if city [ICON_CITIZEN] population is 15 or higher.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION_MMSS',					'+1 [ICON_Amenities] Amenity from Zoos, Botanical Gardens, Aquariums, and Maritime Museums, equal amount of [ICON_SCIENCE] Science if district has at least +4 adjacency bonus, equal amount of [ICON_CULTURE] Culture if city [ICON_CITIZEN] population is 15 or higher.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION_PRESERVE',				'+1 [ICON_Amenities] Amenity from Zoos, Botanical Gardens, and Aquariums, equal amount of [ICON_SCIENCE] Science if city has Preserve district, equal amount of [ICON_CULTURE] Culture if district has at least +4 adjacency bonus.'),
		('LOC_POLICY_JNR_RED_LIST_DESCRIPTION_PRESERVE_MMSS',			'+1 [ICON_Amenities] Amenity from Zoos, Botanical Gardens, Aquariums, and Maritime Museums, equal amount of [ICON_SCIENCE] Science if city has Preserve district, equal amount of [ICON_CULTURE] Culture if district has at least +4 adjacency bonus.');

UPDATE LocalizedText SET Text=Text || '[NEWLINE]Grants [ICON_TOURISM] Tourism equal to its [ICON_GOLD] Gold adjacency once Flight has been researched.' WHERE Language='en_US' AND Tag='LOC_DISTRICT_ENTERTAINMENT_COMPLEX_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Grants [ICON_TOURISM] Tourism equal to its [ICON_GOLD] Gold adjacency once Flight has been researched.' WHERE Language='en_US' AND Tag='LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Grants [ICON_TOURISM] Tourism equal to its [ICON_GOLD] Gold adjacency once Flight has been researched.' WHERE Language='en_US' AND Tag='LOC_DISTRICT_STREET_CARNIVAL_EXPANSION2_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Grants [ICON_TOURISM] Tourism equal to its [ICON_GOLD] Gold adjacency once Flight has been researched.' WHERE Language='en_US' AND Tag='LOC_DISTRICT_WATER_STREET_CARNIVAL_EXPANSION2_DESCRIPTION';
UPDATE LocalizedText SET Text=Text || '[NEWLINE]Grants [ICON_TOURISM] Tourism equal to its [ICON_GOLD] Gold adjacency once Flight has been researched.' WHERE Language='en_US' AND Tag='LOC_DISTRICT_HIPPODROME_EXPANSION2_DESCRIPTION';
--------------------------------------------------------------

