----------------------

UPDATE LocalizedText
SET Text = Text||"[NEWLINE][NEWLINE]{LOC_HANGING_GARDENS_PRESERVE_REBUFF}"
WHERE Tag = "LOC_BUILDING_HANGING_GARDENS_DESCRIPTION";

UPDATE LocalizedText
SET Text = Text||"[NEWLINE][NEWLINE]{LOC_EIFFEL_TOWER_PRESERVE_REBUFF}"
WHERE Tag = "LOC_BUILDING_EIFFEL_TOWER_DESCRIPTION";