-- UC_Light_Text
-- Author: JNR  | Translation by Junky
--------------------------------------------------------------

-- Deutsch
--------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Language,	Tag,																Text)
VALUES	('de_DE',	'LOC_BUILDING_HANGAR_DESCRIPTION_UC_JNR_LIGHT',						'+50% Kampferfahrung für Lufteinheiten, die in dieser Stadt ausgebildet werden.[NEWLINE]Alle Lufteinheiten, die in dieser Stadt ausgebildet werden, beginnen mit einer freien Beförderung.[NEWLINE]+2 Flugzeugkapazität im Flugplatz-Bezirk.'),
		('de_DE',	'LOC_BUILDING_AIRPORT_DESCRIPTION_UC_JNR_LIGHT',					'+1 [ICON_TradeRoute] Handelswegkapazität.[NEWLINE]+25% [ICON_Tourism] Tourismus-Druck dieser Stadt auf andere Zivilisationen, wenn das Spiel in der Moderne ankommt.[NEWLINE][NEWLINE]+1 Flugzeugkapazität im Flugplatz-Bezirk.[NEWLINE]Ermöglicht den Lufttransport von Landeinheiten zwischen Flugplatz-Bezirken mit Flughäfen, wenn die Ausrichtung ''Schneller Einsatz'' freigeschaltet wurde.'),
		('de_DE',	'LOC_BUILDING_LIBRARY_DESCRIPTION_UC_JNR_LIGHT',					'+1 zusätzliche [ICON_Science] Wissenschaft für jedes Zeitalter seit der Errichtung oder jüngsten Reparatur.'),
		('de_DE',	'LOC_BUILDING_UNIVERSITY_DESCRIPTION_UC_JNR_LIGHT',					'+0,2 [ICON_Science] Wissenschaft pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.'),
		('de_DE',	'LOC_BUILDING_MADRASA_DESCRIPTION_UC_JNR_LIGHT',					'Einzigartiges Gebäude von Arabien.[NEWLINE][ICON_Faith] Glaubensbonus in Höhe des Nachbarschaftsbonus des Campus Bezirks.[NEWLINE][NEWLINE]+0,2 [ICON_Science] Wissenschaft pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.'),
		('de_DE',	'LOC_BUILDING_RESEARCH_LAB_DESCRIPTION_UC_JNR_LIGHT',				'Der Basis- [ICON_Culture] Wissenschaftsbonus gilt für alle Stadtzentren im Umkreis von 6 Geländefeldern, die nicht schon einen Bonus durch das Forschungslabor haben.[NEWLINE]+5% [ICON_Science] Wissenschaft in dieser Stadt. Zusätzlich +5% solange die Stadt [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_BUILDING_BANK_DESCRIPTION_UC_JNR_LIGHT',						'+0,4 [ICON_Gold] Gold pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.'),
		('de_DE',	'LOC_BUILDING_STOCK_EXCHANGE_DESCRIPTION_UC_JNR_LIGHT',				'Der Basis- [ICON_Gold] Goldbonus gilt für alle Stadtzentren im Umkreis von 6 Geländefeldern, die nicht schon einen Bonus durch die Börse haben.[NEWLINE]+5% [ICON_Gold] Gold in dieser Stadt. Zusätzlich +5% solange die Stadt [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_BUILDING_ARMORY_DESCRIPTION_UC_JNR_LIGHT',						'+1 [ICON_Production] Produktion für strategische Ressourcen in dieser Stadt.[NEWLINE][NEWLINE]+25% Kampferfahrung für Landeinheiten, die in dieser Stadt ausgebildet werden.[NEWLINE]Strategisches Ressourcen-Vorratslager +10 (bei Standardgeschwindigkeit).'),
		('de_DE',	'LOC_BUILDING_MILITARY_ACADEMY_DESCRIPTION_UC_JNR_LIGHT',			'+25% Kampferfahrung für Landeinheiten, die in dieser Stadt ausgebildet werden.[NEWLINE]All land units trained in this city start with a free promotion.[NEWLINE]Strategisches Ressourcen-Vorratslager +10 (bei Standardgeschwindigkeit).[NEWLINE]Ermöglicht die unmittelbare Ausbildung von Korps und Armeen. Die Ausbildungskosten von Korps und Armeen sinken um 25%.'),
		('de_DE',	'LOC_BUILDING_ARENA_DESCRIPTION_UC_JNR_LIGHT',						'+1 [ICON_Culture] Kultur für [ICON_RESOURCE_HORSES] Pferde in dieser Stadt.'),
		('de_DE',	'LOC_BUILDING_TLACHTLI_DESCRIPTION_UC_JNR_LIGHT',					'Einzigartiges Gebäude für die Azteken.[NEWLINE][NEWLINE]+1 [ICON_Culture] Kultur für Steinbrüche in dieser Stadt.'),
		('de_DE',	'LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION_UC_JNR_LIGHT',				'+1 [ICON_GOLD] Gold für alle Felder der Stadt mit Anziehungskraft Atemberaubend.'),
		('de_DE',	'LOC_BUILDING_SEAPORT_DESCRIPTION_UC_JNR_LIGHT',					'+2 [ICON_GOLD] Gold auf allen Küstenfeldern der Stadt.[NEWLINE][NEWLINE]+25% Kampferfahrung für alle Seeeinheiten, die in dieser Stadt ausgebildet werden.[NEWLINE]Alle Seeeinheiten, die in dieser Stadt ausgebildet werden, beginnen mit einer freien Beförderung.[NEWLINE]Ermöglicht die unmittelbare Ausbildung von Flotten und Armadas.[NEWLINE]Die Ausbildungskosten von Flotten und Armadas sinken um 25%.'),
		('de_DE',	'LOC_BUILDING_WORKSHOP_DESCRIPTION_UC_JNR_LIGHT',					'+0,2 [ICON_Production] Produktion pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.'),
		('de_DE',	'LOC_BUILDING_ELECTRONICS_FACTORY_DESCRIPTION_UC_JNR_LIGHT',		'Einzigartiges Gebäude von Japan.[NEWLINE]Gewährt dieser Stadt +4 [ICON_Culture] Kultur nach der Erforschung der Elektrizität.'),
		('de_DE',	'LOC_BUILDING_COAL_POWER_PLANT_DESCRIPTION_UC_JNR_LIGHT',			'Konvertiert automatisch eine beliebige Menge [ICON_RESOURCE_COAL] Kohle zu [ICON_Power] Energie für Städte im Umkreis von 6 Geländefeldern, die sie jede Runde brauchen. Dabei gilt folgende Rate:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_COAL] Kohle [ICON_PowerRight] 4 [ICON_Power] Energie[NEWLINE][ICON_Bullet]Starke CO2-Belastung der Atmosphäre[NEWLINE]Alle Felder dieser Stadt erhalten -2 Anziehungskraft.[NEWLINE][NEWLINE]Der [ICON_Production] Produktionsbonus wird auf alle Stadtzentren im Umkreis von 6 Geländefeldern erweitert, die nicht bereits über einen Bonus durch ein Kraftwerk verfügen.[NEWLINE]+10% [ICON_Production] Produktion in dieser Stadt solange sie [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_BUILDING_FOSSIL_FUEL_POWER_PLANT_DESCRIPTION_UC_JNR_LIGHT',	'Konvertiert automatisch eine beliebige Menge [ICON_RESOURCE_OIL] Öl zu [ICON_Power] Energie für Städte im Umkreis von 6 Geländefeldern, die sie jede Runde brauchen. Dabei gilt folgende Rate:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_OIL] Öl [ICON_PowerRight] 4 [ICON_Power] Energie[NEWLINE][ICON_Bullet]Moderate CO2-Belastung der Atmosphäre.[NEWLINE]Alle Felder dieser Stadt erhalten -1 Anziehungskraft.[NEWLINE][NEWLINE]Der [ICON_Production] Produktionsbonus wird auf alle Stadtzentren im Umkreis von 6 Geländefeldern erweitert, die nicht bereits über einen Bonus durch ein Kraftwerk verfügen.[NEWLINE]+10% [ICON_Production] Produktion in dieser Stadt solange sie [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_BUILDING_POWER_PLANT_DESCRIPTION_UC_JNR_LIGHT',				'Konvertiert automatisch eine beliebige Menge [ICON_RESOURCE_URANIUM] Uran zu [ICON_Power] Energie für Städte im Umkreis von 6 Geländefeldern, die sie jede Runde brauchen. Dabei gilt folgende Rate:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_URANIUM] Uran [ICON_PowerRight] 16 [ICON_Power] Energie[NEWLINE][ICON_Bullet]Minimale CO2-Belastung der Atmosphäre[NEWLINE]Nach dem Bau des Kernkraftwerks erhöht sich das Risiko eines Nuklearunfalls mit steigendem Alter des Kraftwerks.Der [ICON_Production] Produktions- und [ICON_Science] Wissenschaftsbonus wird auf alle Stadtzentren im Umkreis von 6 Geländefeldern erweitert, die nicht bereits über einen Bonus durch ein Kraftwerk verfügen.[NEWLINE]+10% [ICON_Production] Produktion in dieser Stadt solange sie [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_BUILDING_TEMPLE_DESCRIPTION_UC_JNR_LIGHT',						'+0,2 [ICON_Faith] Glauben pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.[NEWLINE][NEWLINE]Ermöglicht den Kauf von Aposteln, Gurus, Inquisitoren und (mit dem entsprechenden Glaubenssatz) Mönchskriegern. Diese Einheiten können nur mit [ICON_Faith] Glauben erworben werden.'),
		('de_DE',	'LOC_BUILDING_STAVE_CHURCH_DESCRIPTION_UC_JNR_LIGHT',				'Einzigartiges Gebäude von Norwegen.[NEWLINE]Heilige-Stätte-Bezirke erhalten einen zusätzlichen Nachbarschaftsbonus durch Wald. +1 [ICON_PRODUCTION] Produktion für jedes Küstenressourcen-Geländefeld in dieser Stadt.[NEWLINE][NEWLINE]+0,2 [ICON_Faith] Glauben pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.[NEWLINE][NEWLINE]Ermöglicht den Kauf von Aposteln, Gurus, Inquisitoren und (mit dem entsprechenden Glaubenssatz) Mönchskriegern. Diese Einheiten können nur mit [ICON_Faith] Glauben erworben werden.'),
		('de_DE',	'LOC_BUILDING_PRASAT_DESCRIPTION_UC_JNR_LIGHT',						'Einzigartiges Gebäude der Khmer. Ersetzt den Tempel.[NEWLINE]Erforderlich für den Erwerb von Aposteln und Inquisitoren mit [ICON_Faith] Glauben. Missionare, die in dieser Stadt erworben werden, erhalten die Märtyrer-Fähigkeit, die eine [ICON_GreatWork_Relic] Reliquie gewährt, wenn dieser Missionar im theologischen Kampf stirbt.[NEWLINE][NEWLINE]+0,2 [ICON_Faith] Glauben pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.[NEWLINE][NEWLINE]Ermöglicht den Kauf von Aposteln, Gurus, Inquisitoren und (mit dem entsprechenden Glaubenssatz) Mönchskriegern. Diese Einheiten können nur mit [ICON_Faith] Glauben erworben werden.'),
		('de_DE',	'LOC_BUILDING_AMPHITHEATER_DESCRIPTION_UC_JNR_LIGHT',				'+0,2 [ICON_Culture] Kultur pro Runde für jeden [ICON_Citizen] Bürger in der Stadt.'),
		('de_DE',	'LOC_BUILDING_MUSEUM_ART_DESCRIPTION_UC_JNR_LIGHT',					'In dieser Stadt etablierte [ICON_Governor] Gouverneure bringen +1 [ICON_Culture] Kultur für jede verdiente Beförderung, inklusive der ersten.[NEWLINE][NEWLINE]Enthält [ICON_GreatWork_Landscape] Große Kunstwerke.'),
		('de_DE',	'LOC_BUILDING_MUSEUM_ARTIFACT_DESCRIPTION_UC_JNR_LIGHT',			'+3 [ICON_Culture] Kultur für jede [ICON_RESOURCE_ANTIQUITY_SITE] Altertumsstätte und jedes [ICON_RESOURCE_SHIPWRECK] Schiffswrack in dieser Stadt.[NEWLINE][NEWLINE]Enthält [ICON_GreatWork_Artifact] Artefakte.'),
		('de_DE',	'LOC_BUILDING_BROADCAST_CENTER_DESCRIPTION_UC_JNR_LIGHT',			'Der Basis- [ICON_Culture] Kulturbonus gilt für alle Stadtzentren im Umkreis von 6 Geländefeldern, die nicht schon einen Bonus durch das Sendezentrum haben.[NEWLINE]+5% [ICON_Culture] Kultur in dieser Stadt. Zusätzlich +5% solange die Stadt [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_BUILDING_FILM_STUDIO_DESCRIPTION_UC_JNR_LIGHT',				'Einzigartiges Gebäude von Amerika.[NEWLINE]+100% [ICON_Tourism] Tourismus-Druck dieser Stadt auf andere Zivilisationen, wenn das Spiel in der Moderne ankommt.[NEWLINE][NEWLINE]Der Basis- [ICON_Culture] Kulturbonus gilt für alle Stadtzentren im Umkreis von 6 Geländefeldern, die nicht schon einen Bonus durch das Sendezentrum haben.[NEWLINE]+5% [ICON_Culture] Kultur in dieser Stadt. Zusätzlich +5% solange die Stadt [ICON_Power] mit Energie versorgt wird.'),
		('de_DE',	'LOC_POLICY_RATIONALISM_DESCRIPTION_JNR_UC_LIGHT',					'Mehr [ICON_Science] Wissenschaft durch Gebäude im Campus: +1  bei 10 [ICON_CITIZEN] Stadtbevölkerung und mehr, +1 , wenn Nachbarschaftsbonus +3.'),
		('de_DE',	'LOC_POLICY_FREE_MARKET_DESCRIPTION_JNR_UC_LIGHT',					'Mehr [ICON_Gold] Gold durch Gebäude im Handelszentrum: +2 bei 10 [ICON_CITIZEN] Stadtbevölkerung und mehr, +2 , wenn Nachbarschaftsbonus +4.'),
		('de_DE',	'LOC_POLICY_SIMULTANEUM_DESCRIPTION_JNR_UC_LIGHT',					'Mehr [ICON_Faith] Glauben durch Gebäude in Heiligen Stätten: +1 bei 10 [ICON_CITIZEN] Stadtbevölkerung und mehr, +1 , wenn Nachbarschaftsbonus +3.'),
		('de_DE',	'LOC_POLICY_GRAND_OPERA_DESCRIPTION_JNR_UC_LIGHT',					'Mehr [ICON_Culture] Kultur durch Gebäude in Theaterplätzen: +1 bei 10 [ICON_CITIZEN] Stadtbevölkerung und mehr, +1 , wenn Nachbarschaftsbonus +3.');
--------------------------------------------------------------