
INSERT OR REPLACE INTO LocalizedText
		(Language, Tag,	Text)
VALUES
		-- Celebrity Pedia
		("de_DE", 
		"LOC_PEDIA_UNITS_PAGE_UNIT_ROCK_BAND_CHAPTER_HISTORY_PARA_1",					
		"Menschen können auf unterschiedlichste Weise berühmt werden: durch ihren Beruf, durch Auftritte in den Medien oder ganz zufällig. Der Begriff ''sofortige Berühmtheit'' beschreibt jemanden, der in sehr kurzer Zeit zu einer Berühmtheit wird. Jemand, der ein geringes Maß an vorübergehender Berühmtheit erlangt (z. B. durch einen Hype oder die Massenmedien), kann als ''B-Promi'' bezeichnet werden. Oft wird diese Verallgemeinerung auch auf jemanden angewandt, der nicht den Status eines Mainstreams oder einer dauerhaften Berühmtheit erlangt, sondern versucht, ihn zu erweitern oder auszunutzen."),

		("de_DE", 
		"LOC_PEDIA_UNITS_PAGE_UNIT_ROCK_BAND_CHAPTER_HISTORY_PARA_2",					
		"Dank Publikationen wie People, Boulevardzeitungen wie Star und The National Enquirer und Talkshows, in denen sowohl Prominente als auch vermeintlich gewöhnliche Menschen ihr Leben für die Öffentlichkeit preisgeben, hat das Gefühl der Andersartigkeit der Berühmten abgenommen. Nahaufnahmen, Führungen durch die Häuser von Berühmtheiten, wie sie von Edward R. Murrows Fernsehsendung Mensch zu Mensch ins Leben gerufen wurden, und intime Einblicke in das Leben von Berühmtheiten, wie sie von Barbara Walters und Sendungen wie Today und 60 Minutes für das Fernsehen entwickelt wurden, haben das Gefühl der Öffentlichkeit für Berühmtheiten verändert. Die Amerikaner werden vor allem durch die visuellen Medien dazu verleitet, zu glauben, dass sie Prominente ganz genau kennen."),

		("de_DE", 
		"LOC_PEDIA_UNITS_PAGE_UNIT_ROCK_BAND_CHAPTER_HISTORY_PARA_3",					
		"Die Kultur der Berühmtheiten ist eine symbiotische Geschäftsbeziehung, bei der die Künstler Reichtum, Ehre und soziale Macht im Gegenzug dafür erhalten, dass sie dem Publikum ein Gefühl von Intimität vermitteln. Enorme Gehälter sind an der Tagesordnung. Multimillionen-Dollar-Verträge für Sportler verblassen im Vergleich zu den Einnahmen aus der Werbung, die der Basketballspieler Michael Jordan für Schuhe, Softdrinks, Unterwäsche und Hamburger macht. Berühmte Persönlichkeiten nehmen auch an öffentlichen Medienveranstaltungen teil, wenn sie Ehrungen und Auszeichnungen erhalten, wie z. B. den Cy Young Award für Baseballspieler, die Grammys für Plattenstars und die Oscars für Filmstars. Obwohl es sicherlich schwierig ist, die soziale Macht von Berühmtheiten zu messen, deutet die umstrittene Behauptung des Beatles John Lennon, dass ''die Beatles beliebter sind als Jesus'', auf die Art von Grandiosität hin, die die Kultur der Berühmtheiten begünstigt."),

		("de_DE", 
		"LOC_PEDIA_UNITS_PAGE_UNIT_ROCK_BAND_CHAPTER_HISTORY_PARA_4",					
		"Für den Fan kann die Promi-Kultur bei Rockkonzerten, Sportarenen und anderen Darbietungen des Fantasieobjekts - ob live oder aufgezeichnet und mechanisch reproduziert - zu einer intensiven Identifikation führen. Solche Identifikationen können zu einem Rollentausch führen, bei dem der Fan den Reichtum, die Ehre und die vermeintliche Macht des Prominenten begehrt."),
		-- Promotion: Photo Op (Wonders. At least 2 Paragraphs)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_ALBUM_COVER_ART_CHAPTER_HISTORY_PARA_1",					
		"Ein Fototermin (manchmal auch Foto-Opp), kurz für Fotogelegenheit, ist eine arrangierte Gelegenheit, ein Foto von einem Politiker, einer Berühmtheit oder einem bemerkenswerten Ereignis zu machen, insbesondere an einem ikonischen Ort. dministration von US-Präsident Richard Nixon. William Safire schrieb den Begriff Bruce Whelihan zu, einem Assistenten von Nixons Pressesprecher Ron Ziegler. Ziegler sagte: ''Holt sie für ein Foto herein'', und Whelihan verkündete pflichtbewusst im Presseraum des Weißen Hauses: ''Es wird einen Fototermin im Oval Office geben.''"),

		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_ALBUM_COVER_ART_CHAPTER_HISTORY_PARA_2",					
		"Der Begriff hat einen negativen Beigeschmack und bezieht sich auf ein sorgfältig geplantes Pseudo-Ereignis, das oft als Nachricht getarnt ist. Mit dem Aufkommen von Kongressen und sozialen Medien nutzen Prominente jedoch jede Gelegenheit, um Fotos zu machen, die es in die Nachrichten schaffen oder die ihnen mehr Reichweite auf Online-Plattformen verschaffen."),
		-- Promotion: Professional Athlete (Fairgrounds. At least 1 Paragraphs)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_ARENA_ROCK_CHAPTER_HISTORY_PARA_1",					
		"Profisportler betreiben Sport für ihren Lebensunterhalt. Sie haben durch jahrelanges Training eine Spitzenposition in ihrem gewählten Bereich erreicht. Profisportler sind Menschen mit natürlichem Talent, Ausdauer und Leistungswillen. Sie verfügen über ausgezeichnete Reflexe und Koordinationsfähigkeiten und sind sehr diszipliniert, wenn es um rigoroses Training geht. Profisportler werden von Sportfans oft als Berühmtheiten verehrt, was so weit geht, dass Sammelkarten mit den wichtigsten Sportlern der Welt verkauft werden."),

		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_ARENA_ROCK_CHAPTER_HISTORY_PARA_2",					
		"Die meisten Profisportler sind aus den Reihen guter Amateursportler hervorgegangen. Amateursportler spielen aus Freude an Wettkämpfen und Siegen und gelegentlich auch für Auszeichnungen wie olympische Medaillen. Einige spielen für Schulen, Hochschulen, Vereine oder in Turnieren. Im Gegensatz zu Amateursportlern verdienen Profisportler jedoch Geld für ihre sportliche Betätigung. Sie spielen für gewinnorientierte Mannschaften - professionelle Fußball-, Baseball-, Basketball- und Eishockeymannschaften, um nur einige zu nennen. In Einzelsportarten wie Golf, Tennis und Boxen nehmen die Sportler an Turnieren teil, bei denen der Sieger ein Preisgeld erhält."),
		-- Promotion: Musical Theatre (Theater Square. At least 1 Paragraphs)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_GLAM_ROCK_CHAPTER_HISTORY_PARA_1",					
		"Musiktheater ist eine Form der Theateraufführung, die Lieder, gesprochene Dialoge, Schauspiel und Tanz miteinander verbindet. Die Geschichte und der emotionale Inhalt eines Musicals - Humor, Pathos, Liebe, Wut - werden durch Worte, Musik, Bewegung und technische Aspekte der Unterhaltung als ein integriertes Ganzes vermittelt. Obwohl sich das Musiktheater mit anderen Theaterformen wie der Oper und dem Tanz überschneidet, zeichnet es sich dadurch aus, dass der Musik die gleiche Bedeutung beigemessen wird wie dem Dialog, der Bewegung und anderen Elementen. Seit dem frühen 20. Jahrhundert werden Musiktheaterstücke im Allgemeinen einfach als Musicals bezeichnet."),

		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_GLAM_ROCK_CHAPTER_HISTORY_PARA_2",					
		"Das moderne westliche Musiktheater entstand im 19. Jahrhundert, wobei viele strukturelle Elemente durch die Werke von Gilbert und Sullivan in Großbritannien und von Harrigan und Hart in Amerika geschaffen wurden. Es folgten die zahlreichen Edwardianischen Musikkomödien und die Musiktheaterwerke amerikanischer Schöpfer wie George M. Cohan an der Wende zum 20. Die Musicals des Princess Theatre (1915-1918) und andere intelligente Shows wie Of Thee I Sing (1931) waren ein künstlerischer Fortschritt gegenüber den Revuen und anderen schaumigen Unterhaltungen des frühen 20. Jahrhunderts und führten zu so bahnbrechenden Werken wie Show Boat (1927) und Oklahoma! (1943). Zu den berühmtesten Musicals der folgenden Jahrzehnte gehören West Side Story (1957), The Fantasticks (1960), Hair (1967), A Chorus Line (1975), Les Misérables (1985), The Phantom of the Opera (1986), Rent (1996), The Producers (2001), Wicked (2003) und Hamilton (2015)."),
		-- Press Coverage (Tourism reach. At least 1)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_GOES_TO_CHAPTER_HISTORY_PARA_1",					
		"Die Welt der Prominenten und die Massenmedien sind untrennbar miteinander verbunden und stehen in einer Beziehung, die sowohl für beide Seiten vorteilhaft als auch destruktiv ist. Die Kultur der Prominenten ist tief in den Medien verwurzelt. Ohne die Öffentlichkeit, die sie durch die Medien erlangt hat, würde es sie nicht geben, und ohne ihre kontinuierliche Beziehung zu den Medien wäre sie heute sicherlich nicht so bekannt. Auch die Medien profitieren davon, da sie durch die ständige Berichterstattung über die Welt der Prominenten die Aufmerksamkeit der Öffentlichkeit auf sich ziehen können. Da die Medien versuchen, die Aufmerksamkeit der Öffentlichkeit auf sich zu ziehen und zu halten, sind sie oft sehr temperamentvoll in ihrem Umgang mit Prominenten. Sie bauen sie auf, um sie in der Zukunft wieder zu Fall zu bringen. Dies lässt sich an Persönlichkeiten wie Britney Spears und Michael Jackson erkennen. Britney Spears zum Beispiel erlangte in den Jahren ihres größten Erfolges eine enorme Popularität und ein positives Medienecho. Nachdem es mit ihrer Karriere bergab ging, wie z. B. bei dem Vorfall im Jahr 2007, als sie sich den Kopf rasierte, griffen die Medien auf die Idee zurück, dass sie eine instabile Figur sei, was es ihnen ermöglichte, auf diese Weise über sie zu berichten und weiterhin Inhalte über sie zu produzieren, obwohl ihre Popularität als Künstlerin abnahm (siehe das obige Video über die intensive Medienberichterstattung über Spears' Frisurenwechsel). Ähnlich verhält es sich mit Michael Jackson: Als seine Popularität als Künstler abnahm, hörten die Medien auf, ihn in einem positiven Licht zu porträtieren, und konzentrierten sich stattdessen auf das Negative, um die öffentliche Aufmerksamkeit aufrechtzuerhalten."),

		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_GOES_TO_CHAPTER_HISTORY_PARA_2",					
		"Berühmte Persönlichkeiten können für ihre Auszeichnungen angefeindet werden, und die Öffentlichkeit kann eine Hassliebe zu Berühmtheiten haben. Da das Privatleben von Prominenten sehr präsent ist, werden ihre Erfolge und Unzulänglichkeiten oft sehr öffentlich gemacht. Prominente werden abwechselnd als leuchtende Beispiele für Perfektion dargestellt, wenn sie Auszeichnungen erhalten, oder als dekadent oder unmoralisch, wenn sie mit einem Skandal in Verbindung gebracht werden. Wenn sie in einem positiven Licht gesehen werden, werden Prominente häufig so dargestellt, als besäßen sie Fähigkeiten und Fertigkeiten, die über die des Durchschnittsmenschen hinausgehen. In ähnlicher Weise werden einige Prominente mit sehr geringer formaler Bildung manchmal als Experten für komplizierte Themen dargestellt. Einige Prominente haben sich sehr deutlich zu ihren politischen Ansichten geäußert. So äußerte Matt Damon beispielsweise seinen Unmut über die 2008 nominierte US-Vizepräsidentschaftskandidatin Sarah Palin sowie über die Schuldenkrise in den Vereinigten Staaten im Jahr 2011."),
		-- Countercultural Icon (Loyalty)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_INDIE_CHAPTER_HISTORY_PARA_1",					
		"Gegenkultur ist ein gesellschaftspolitischer Begriff, der einen Dissens zwischen den vorherrschenden Ideologien oder dem Mainstream und alternativen Wertesystemen bezeichnet, wodurch eine kollektive Stimme entsteht, die als bedeutende Minderheit angesehen werden kann. Die gegenkulturelle Bewegung entstand Mitte der 1960er Jahre als Selbstbezeichnung junger Menschen innerhalb der bürgerlichen Jugendbewegung, als die Politik mit kulturellen Fragen verschmolz. Die Themen Rassismus, Absprachen zwischen Hochschuleinrichtungen und dem Militär und den Unternehmen zur Unterstützung des Vietnamkriegs und die Regelung der elterlichen Sorge an Hochschulen und Universitäten verschmolzen mit Kämpfen um Haarlänge, Gemeinschaftsleben, Musikgeschmack, Drogenkonsum, Geschlechterrollen und Sexualität."),

		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_INDIE_CHAPTER_HISTORY_PARA_2",					
		"Im Laufe dieser Ära entstanden neue kulturelle Formen und eine dynamische Subkultur, die das Experimentieren, moderne Inkarnationen der Bohème, den Aufstieg der Hippies und andere alternative Lebensstile zelebrierte. Besonders bemerkenswert ist diese Kreativität in den Werken von Musikern wie den Beatles und Bob Dylan sowie von New-Hollywood-Filmemachern, deren Werke weit weniger von der Zensur eingeschränkt wurden. Innerhalb und über viele Disziplinen hinweg trugen viele andere kreative Künstler, Autoren und Denker dazu bei, die Bewegung der Gegenkultur zu definieren. Die Alltagsmode erlebte einen Rückgang des Anzugs und vor allem des Tragens von Hüten; die auf Jeans basierenden Stile für Männer und Frauen wurden zu einer wichtigen Modebewegung, die bis heute anhält."),
		-- Environmentalist (Natural Wonders)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_MUSIC_FESTIVAL_CHAPTER_HISTORY_PARA_1",					
		"Ein Umweltschützer ist eine Person, die sich für unsere natürliche Umwelt und die nachhaltige Bewirtschaftung ihrer Ressourcen durch Veränderungen in der öffentlichen Politik oder im individuellen Verhalten einsetzt. Dies kann die Unterstützung von Praktiken wie bewusster Konsum, Naturschutzinitiativen, Investitionen in erneuerbare Ressourcen, verbesserte Effizienz in der Materialwirtschaft, der Übergang zu neuen Buchhaltungsparadigmen wie der Ökologischen Ökonomie, die Erneuerung und Wiederbelebung unserer Verbindungen mit nicht-menschlichem Leben oder sogar die Entscheidung, ein Kind weniger zu haben, um den Verbrauch und den Druck auf die Ressourcen zu reduzieren, beinhalten. Umweltschützer und Umweltorganisationen bemühen sich auf verschiedene Weise (z. B. durch Basisaktivismus und Proteste) darum, der natürlichen Welt eine stärkere Stimme in menschlichen Angelegenheiten zu verleihen."),

		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_MUSIC_FESTIVAL_CHAPTER_HISTORY_PARA_2",					
		"Das Engagement von Prominenten für den Umweltschutz hat in den letzten Jahrzehnten dramatisch zugenommen. Organisationen wie die Surfrider Foundation, Oceana, die Ian Somerhalder Foundation und Heal the Bay bestehen aus engagierten Umweltschützern sowie aus prominenten Gründern und Unterstützern. Mit dem Aufkommen der sozialen Medien und der neuen digitalen Landschaft hat sich das Spektrum der prominenten Befürworter von Umwelt- und Philanthropieprojekten vergrößert, da es für Prominente so einfach geworden ist, einen Beitrag zu leisten oder eine Organisation öffentlich zu unterstützen, wie ein Fingertipp auf dem Bildschirm eines Telefons."),
		-- Glamorous Lifestyle (Gold)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_POP_CHAPTER_HISTORY_PARA_1",					
		"Glamour ist der Eindruck von Anziehungskraft oder Faszination, den eine besonders luxuriöse oder elegante Erscheinung erzeugt, ein Eindruck, der die Realität verstärkt. Typischerweise kann eine Person, ein Ereignis, ein Ort, eine Technologie oder ein Produkt wie ein Kleidungsstück glamourös sein oder Glamour verleihen. Ursprünglich bezog sich der Begriff ''Glamour'' auf einen Zauber, eine Illusion, die angeblich von Hexen erzeugt wird. Die Hollywood-Studios präsentierten ihre weiblichen Stars in Designer-Kleidern und exquisitem Schmuck, sowohl auf der Leinwand als auch bei sorgfältig inszenierten Werbeauftritten. Joan Crawford soll gesagt haben: ''Ich gehe nie aus dem Haus, wenn ich nicht wie Joan Crawford, der Filmstar, aussehe''."),
		
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_POP_CHAPTER_HISTORY_PARA_2",					
		"Prominente gelten als glamourös, wenn sie gewöhnliche Aufgaben auf eine andere, luxuriösere oder extravagantere Weise erledigen. Virushkas Hochzeit, die das Internet in Brand setzte, war die glamouröseste Hochzeit der B-Town bis jetzt. Von der Location über die Dekoration bis hin zu den Outfits und den riesigen Summen, die ausgegeben wurden, war alles anders als bei einer gewöhnlichen Männerhochzeit. All diese Faktoren zusammen haben die Neugierde auf diese Verbindung von Cricket und Bollywood wie nie zuvor geweckt. Der Prominentenstatus eines Prominenten bleibt erhalten, solange sich die Fans für seinen Lebensstil interessieren, und diese Neugier wird durch Glamour gewährleistet. Glamour ist das Wichtigste im Lebensstil eines Prominenten, denn in dem Moment, in dem der Glamour verloren geht, geht auch die Neugierde verloren und damit der ganze Hype um den Prominenten. Die Tatsache, dass sie das haben, was wir wollen, macht den Lebensstil eines Prominenten glamourös. Egal, wie groß unser Haus ist oder wie sehr wir es lieben, wenn wir die Chance hätten, in Antilla, dem milliardenschweren Haus von Mukesh Ambani, zu wohnen, würden wir sofort zugreifen."),
		-- Crocodile Hunter (Waterparks)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_REGGAE_ROCK_CHAPTER_HISTORY_PARA_1",					
		"Der Krokodiljäger ist eine Fernsehserie über Wildtiere, die von Steve Irwin und seiner Frau Terri moderiert wurde. Die Serie wurde durch Irwins unkonventionelle Herangehensweise an die Tierwelt zu einem beliebten Franchise. Sie zog eine Reihe von Projekten nach sich, darunter den Spielfilm The Crocodile Hunter: Collision Course und zwei Fernsehspinoffs: Croc Files und The Crocodile Hunter Diaries. Die Serie wurde auf Animal Planet ausgestrahlt, wo sie zu der Zeit die höchste Einschaltquote des Senders hatte, und wurde von Sendern auf der ganzen Welt syndiziert."),
		
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_REGGAE_ROCK_CHAPTER_HISTORY_PARA_2",					
		"Die Show war so erfolgreich, dass daraus eine Serie mit dem Titel ''The Crocodile Hunter'' (Der Krokodiljäger) entstand, von der Irwin seinen Spitznamen übernahm. Die von Irwin und Terri moderierte Fernsehserie wurde international ausgestrahlt und war ein großer Erfolg bei Tierliebhabern auf der ganzen Welt. Neben seiner Fernseharbeit, bei der er in internationalen Talkshows auftrat, Cameo-Rollen in Filmen spielte und andere Wildtierprogramme präsentierte, setzte Irwin die Verbesserungen und Erweiterungen des von seinen Eltern gegründeten Wildparks fort. Ein großer Schritt war die Umbenennung des Parks in Australia Zoo im Jahr 1998. Irwins Ansatz des ''Schutzes durch aufregende Bildung'' zog sich durch alle Bereiche seiner Arbeit und Irwin hoffte, dass sein Park eines Tages der beste Zoo der Welt werden würde. Auch die Familie spielte in Irwins Leben eine große Rolle. Zusammen mit Terri teilte er seine Liebe zur Tierwelt mit seinen beiden Kindern Bindi und Robert, die in die Fußstapfen ihres Vaters zu treten schienen."),
		-- Televangelist (Religious Conversion)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_RELIGIOUS_ROCK_CHAPTER_HISTORY_PARA_1",					
		"Unter Televangelismus versteht man die Nutzung der Medien, insbesondere von Radio und Fernsehen, zur Verbreitung des Christentums. Televangelisten sind offizielle oder selbsternannte Geistliche, die einen großen Teil ihres Dienstes der Fernsehübertragung widmen. Einige Televangelisten sind auch reguläre Pastoren oder Seelsorger in ihren eigenen Gotteshäusern (oft eine Megakirche), aber die meisten ihrer Anhänger kommen aus dem Fernseh- und Radiopublikum. Andere haben keine herkömmliche Gemeinde und arbeiten hauptsächlich über das Fernsehen. Der Begriff wird von Kritikern auch spöttisch als Anspielung auf die Selbstverherrlichung solcher Geistlicher verwendet."),
		
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_RELIGIOUS_ROCK_CHAPTER_HISTORY_PARA_2",					
		"Der Televangelismus ist ein typisch amerikanisches Phänomen, das auf die weitgehende Deregulierung der Medien zurückzuführen ist, wo der Zugang zu Fernsehsendern und Kabelfernsehen praktisch jedem offen steht, der es sich leisten kann, und auf eine große christliche Bevölkerung, die in der Lage ist, die notwendigen Mittel bereitzustellen. Besonders populär wurde es bei evangelikalen protestantischen Zuschauern, ob unabhängig oder in christlichen Konfessionen organisiert. Die zunehmende Globalisierung des Rundfunks hat es jedoch einigen amerikanischen Fernsehpredigern ermöglicht, über internationale Rundfunknetze ein größeres Publikum zu erreichen, darunter auch solche, die speziell christlich ausgerichtet sind, wie Trinity Broadcasting Network und The God Channel. In einigen anderen Ländern, wie z. B. Brasilien, gibt es zunehmend inländisch produzierte Fernsehpredigten."),
		-- Private Jets (Movement)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_ROADIES_CHAPTER_HISTORY_PARA_1",					
		"Ein Geschäftsflugzeug, Privatjet oder Bizjet ist ein Düsenflugzeug, das für den Transport kleinerer Personengruppen konzipiert ist. Geschäftsflugzeuge können auch für andere Zwecke eingesetzt werden, z. B. für die Evakuierung von Verletzten oder die Expresszustellung von Paketen, und einige werden von öffentlichen Einrichtungen, Regierungsbeamten oder den Streitkräften sowie von Prominenten als Teil ihres VIP-Lifestyles genutzt."),
		
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_ROADIES_CHAPTER_HISTORY_PARA_2",					
		"In vielerlei Hinsicht erinnert die luxuriöse Ausstattung der Kabinen von Privatjets an den Glamour der 1940er Jahre, als Butler die Passagiere in den ersten kommerziellen Flugzeugen im Smoking bedienten. Während kommerzielle Flugreisen zugänglicher geworden sind und heute fast jeder in Trainingsanzug und Turnschuhen einen gleichgültigen Service genießen kann, bieten Privatjet-Reisen eine Rückkehr zu Glamour und Luxus - nur mit viel höherer Geschwindigkeit und mit Wi-Fi an Bord. All dies wäre ganz nach dem Geschmack von Frank Sinatra gewesen, der die Entwicklung der Bordunterhaltung auf Langstreckenflügen ebenso zu schätzen gewusst hätte. Von der ersten Filmvorführung an Bord im Jahr 1925 (der Stummfilm The Lost World auf einem Flug von London) bis hin zu persönlichen Bildschirmen, die den Passagieren im 21. Jahrhundert Hunderte von Filmen und Spielen zur Verfügung stellen, hat die Art und Weise, wie wir uns in der Luft unterhalten, ebenso viele Fortschritte und Innovationen erfahren wie die Triebwerke, die unsere Flugzeuge durch den Himmel treiben. Die Charterflüge mit Privatjets setzen immer neue Maßstäbe, mit Wi-Fi-Geschwindigkeiten, die Live-Streaming ermöglichen, und Kabinen, die geräumig genug sind, um Fitnessgeräte an Bord zu bringen und während der Reise zu trainieren."),
		-- Science Guy (Campus and Spaceport)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_SPACE_ROCK_CHAPTER_HISTORY_PARA_1",					
		"Bill Nye der Wissenschaftsjunge ist eine amerikanische halbstündige Live-Action-Wissenschaftssendung, die von KCTS Seattle und McKenna/Gottlieb Producers produziert wird. Sie wurde im Wesentlichen von der National Science Foundation finanziert. Nachdem die Produzenten eine Vertriebsvereinbarung mit Buena Vista Television geschlossen hatten, wurde die Sendung auf den Markt gebracht. Nye stellt einen hyperkinetischen, großen und schlanken Wissenschaftler dar, der einen blauen Laborkittel und eine Fliege trägt. Er verbindet die ernsthafte Wissenschaft von alltäglichen Dingen mit rasanter Action und Humor. Jede halbstündige Sendung beginnt mit einer Eröffnungssequenz, in der Nye das Thema der Folge vorstellt, die in eine Vorspannsequenz übergeht, in der Nye in einer computeranimierten wissenschaftlichen Welt zu sehen ist, in der sich sein Kopf dreht, Radiofrequenzen zu hören sind und Plastikspielzeug-Dinosaurier fliegen. Wissenschaftsbezogene TV- und Filmparodien konfigurieren die Fakten des Episodenthemas, zusammen mit Parodien von TV-Werbung. In der Sendung gab es viele Gastauftritte. In jeder Folge besuchte Nye viele Orte, die mit dem Thema der Folge zu tun hatten, und zeigte Interviews mit Menschen, die über ihre Arbeit und andere Beiträge sprachen. Am Ende jeder Folge bedankt sich Nye bei den Zuschauern für das Zuschauen, bevor er in einer cleveren Beschreibung die Aktivität eines Themas erklärt."),
		
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_SPACE_ROCK_CHAPTER_HISTORY_PARA_2",					
		"In den USA inspirierte Bill Nye eine ganze Generation von Wissenschaftlern und Wissenschaftsbegeisterten. Die Sendung wurde für 23 Emmy-Preise nominiert und gewann 19 von ihnen. Und vom pädagogischen Standpunkt aus betrachtet, hat sie funktioniert. An Grund- und Mittelschulen in den USA ersetzte die Show oft den naturwissenschaftlichen Unterricht an Tagen, an denen die Lehrerinnen und Lehrer frei hatten - etwas, worüber Nye auf einer Jahrestagung der National Science Teachers Association in dem Dokumentarfilm Bill Nye: Science Guy von 2017 scherzte."),
		--Beach Parties (Harbors and Seaside Resorts)
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_SURF_ROCK_CHAPTER_HISTORY_PARA_1",					
		"Strandpartys entwickelten sich als Teil der Surfkultur in den 1960er Jahren. Zu den Aspekten der Surfkultur der 1960er Jahre in Südkalifornien, wo sie zuerst populär wurde, gehören der Woodie, Bikinis und andere Strandkleidung, wie Boardshorts oder Baggies, sowie Surfmusik. Sie inspirierten schließlich das Beach-Party-Genre, das sich durch die Verwendung von Elementen der Surf-Kultur und einer unbeschwerten Anziehungskraft auf die Teenager der damaligen Zeit konzentrierte."),
		
		("de_DE", 
		"LOC_PEDIA_UNITPROMOTIONS_PAGE_PROMOTION_SURF_ROCK_CHAPTER_HISTORY_PARA_2",					
		"Strandpartyfilme waren ein Mitte der 1960er Jahre beliebtes Film-Subgenre, das mit dem Frankie Avalon/Annette Funicello-Hit Beach Party im Jahr 1963 begann. Insgesamt wurden in den 1960er Jahren ein paar Dutzend Titel dem Beach-Party-Genre zugeordnet. Die meisten von ihnen waren Low-Budget-B-Filme, fast alle waren Komödien und setzten auf alberne Handlungen, Teenie-Trends, romantische Geschichten, musikalische Einlagen und eine augenzwinkernde Art von Anspielungskomödie. Sie waren dumm, fröhlich, bunt und musikalisch. Sie appellierten an die Unbeschwertheit der Menschen in den 1960er Jahren und hatten einen großen, unerwarteten Erfolg beim Publikum.");
		